/**
 * One-off generator: emits the catalog seed migrations from the real bundled
 * catalog, so the seeds can never drift from the app. Run via esbuild so it
 * reads the actual TS source:
 *
 *   ./node_modules/.bin/esbuild scripts/gen-catalog-seed.ts --bundle \
 *     --platform=node --format=esm --outfile=scratchpad/gen.mjs && node scratchpad/gen.mjs
 *
 * Emits:
 *   0003_seed_si_activities.sql  — special_interests + activities
 *   0004_seed_providers_subregions.sql — providers + sub_regions
 * Re-run whenever the catalog changes to refresh the seeds.
 */
import { writeFileSync } from "node:fs";
import { SIS, SUBREGIONS } from "../src/data/taxonomy";
import { ACTIVITIES, PROVIDERS, DESTINATIONS, GUIDES } from "../src/data/places";

const q = (s: string | null | undefined) => (s == null ? "null" : `'${s.replace(/'/g, "''")}'`);

const siRows = SIS.map(
  (s) => `  (${q(s.id)}, ${q(s.name)}, ${q(s.sig)}, ${q(s.status)}, ${q(s.accent)}, ${s.lux}, ${q(s.group)})`
).join(",\n");

const actRows = Object.entries(ACTIVITIES)
  .flatMap(([siId, acts]) =>
    acts.map((a, i) => `  (${q(siId)}, ${q(a.id)}, ${q(a.name)}, ${q(a.well)}, ${q(a.line)}, ${i})`)
  )
  .join(",\n");

const sql = `-- TravelWell.World — seed the Special Interests + Activities catalog.
--
-- GENERATED by scripts/gen-catalog-seed.ts from the bundled catalog (SIS +
-- ACTIVITIES, including David's special-interests.json). Do not hand-edit —
-- regenerate after catalog changes. Idempotent (ON CONFLICT DO UPDATE), so it
-- doubles as the refresh path and the next slice of catalog -> DB.
--
-- Apply:  supabase db push   (or paste into the Supabase SQL editor)
-- Requires 0001 (tables) and 0002 (wells, for the activities.well FK).

-- Special Interests -----------------------------------------------------------
insert into public.special_interests (id, name, signature, status, accent, is_lux, grp) values
${siRows}
on conflict (id) do update set
  name = excluded.name, signature = excluded.signature, status = excluded.status,
  accent = excluded.accent, is_lux = excluded.is_lux, grp = excluded.grp;

-- Activities ------------------------------------------------------------------
-- Laddered experiences per Special Interest. si_id is a plain key (not all
-- activity groups map to a canonical SI in the prototype); well FKs to wells.
create table if not exists public.activities (
  si_id     text not null,
  id        text not null,
  name      text not null,
  well      text not null references public.wells(id),
  line      text,
  position  int not null default 0,
  primary key (si_id, id)
);

alter table public.activities enable row level security;
do $$
begin
  create policy "read activities" on public.activities for select using (true);
exception when duplicate_object then null;
end $$;

insert into public.activities (si_id, id, name, well, line, position) values
${actRows}
on conflict (si_id, id) do update set
  name = excluded.name, well = excluded.well, line = excluded.line, position = excluded.position;
`;

writeFileSync("supabase/migrations/0003_seed_si_activities.sql", sql);
console.log("Wrote supabase/migrations/0003_seed_si_activities.sql");
console.log(`  ${SIS.length} special interests, ${Object.values(ACTIVITIES).flat().length} activities`);

// ---------------------------------------------------------------------------
// 0004 — Providers + Sub-regions
// ---------------------------------------------------------------------------
const provRows = Object.values(PROVIDERS)
  .flat()
  .map((p) => `  (${q(p.name)}, ${q(p.well)}, ${q(p.tier)}, ${q(p.price)}, ${q(p.mode)}, ${q(p.desc)}, ${q(p.commission)})`)
  .join(",\n");

const subRows = Object.entries(SUBREGIONS)
  .flatMap(([code, names]) => names.map((name, i) => `  (${q(code)}, ${q(name)}, ${i})`))
  .join(",\n");

const sql4 = `-- TravelWell.World — seed Providers + Sub-regions.
--
-- GENERATED by scripts/gen-catalog-seed.ts from the bundled catalog (PROVIDERS
-- in places.ts + SUBREGIONS in taxonomy.ts). Do not hand-edit — regenerate
-- after catalog changes. Idempotent (ON CONFLICT DO UPDATE).
--
-- Apply:  supabase db push   (or paste into the Supabase SQL editor)
-- Requires 0001 (providers table + RLS) and 0002 (wells/regions, for the FKs).

-- Providers -------------------------------------------------------------------
-- The providers table (0001) has a generated uuid pk; add a natural key so the
-- seed is idempotent and can act as the refresh path.
create unique index if not exists providers_name_well_key on public.providers (name, well);

insert into public.providers (name, well, tier, price, mode, description, commission) values
${provRows}
on conflict (name, well) do update set
  tier = excluded.tier, price = excluded.price, mode = excluded.mode,
  description = excluded.description, commission = excluded.commission;

-- Sub-regions -----------------------------------------------------------------
create table if not exists public.sub_regions (
  region_code text not null references public.regions(code) on delete cascade,
  name        text not null,
  position    int not null default 0,
  primary key (region_code, name)
);

alter table public.sub_regions enable row level security;
do $$
begin
  create policy "read sub_regions" on public.sub_regions for select using (true);
exception when duplicate_object then null;
end $$;

insert into public.sub_regions (region_code, name, position) values
${subRows}
on conflict (region_code, name) do update set position = excluded.position;
`;

writeFileSync("supabase/migrations/0004_seed_providers_subregions.sql", sql4);
console.log("Wrote supabase/migrations/0004_seed_providers_subregions.sql");
console.log(`  ${Object.values(PROVIDERS).flat().length} providers, ${Object.values(SUBREGIONS).flat().length} sub-regions`);

// ---------------------------------------------------------------------------
// 0005 — Destinations + Guides
// ---------------------------------------------------------------------------
const destRows = Object.entries(DESTINATIONS)
  .flatMap(([code, list]) =>
    list.map((d, i) => `  (${q(d.id)}, ${q(code)}, ${q(d.name)}, ${q(d.country)}, ${q(d.line)}, ${q(d.status)}, ${q(d.img)}, ${i})`)
  )
  .join(",\n");

const guideRows = GUIDES.map(
  (g, i) =>
    `  (${q(g.id)}, ${q(g.type)}, ${q(g.title)}, ${q(g.lede)}, ${q(g.read)}, ${q(g.updated)}, ${q(g.img)}, ${q(g.si)}, ${q(g.region)}, ${i})`
).join(",\n");

const sql5 = `-- TravelWell.World — seed Destinations + Guides.
--
-- GENERATED by scripts/gen-catalog-seed.ts from the bundled catalog
-- (DESTINATIONS + GUIDES in places.ts). Do not hand-edit — regenerate after
-- catalog changes. Idempotent (ON CONFLICT DO UPDATE).
--
-- Apply:  supabase db push   (or paste into the Supabase SQL editor)
-- Requires 0001 (tables) and 0002 (regions, for the destinations.region_code FK).

-- Destinations ----------------------------------------------------------------
create table if not exists public.destinations (
  id          text primary key,
  region_code text not null references public.regions(code) on delete cascade,
  name        text not null,
  country     text not null,
  line        text not null,
  status      text not null check (status in ('live','stub')),
  img         text not null,
  position    int not null default 0
);

alter table public.destinations enable row level security;
do $$
begin
  create policy "read destinations" on public.destinations for select using (true);
exception when duplicate_object then null;
end $$;

insert into public.destinations (id, region_code, name, country, line, status, img, position) values
${destRows}
on conflict (id) do update set
  region_code = excluded.region_code, name = excluded.name, country = excluded.country,
  line = excluded.line, status = excluded.status, img = excluded.img, position = excluded.position;

-- Guides ----------------------------------------------------------------------
create table if not exists public.guides (
  id        text primary key,
  type      text not null,
  title     text not null,
  lede      text not null,
  read      text not null,
  updated   text not null,
  img       text not null,
  si        text not null,
  region    text not null,
  position  int not null default 0
);

alter table public.guides enable row level security;
do $$
begin
  create policy "read guides" on public.guides for select using (true);
exception when duplicate_object then null;
end $$;

insert into public.guides (id, type, title, lede, read, updated, img, si, region, position) values
${guideRows}
on conflict (id) do update set
  type = excluded.type, title = excluded.title, lede = excluded.lede, read = excluded.read,
  updated = excluded.updated, img = excluded.img, si = excluded.si, region = excluded.region,
  position = excluded.position;
`;

writeFileSync("supabase/migrations/0005_seed_destinations_guides.sql", sql5);
console.log("Wrote supabase/migrations/0005_seed_destinations_guides.sql");
console.log(`  ${Object.values(DESTINATIONS).flat().length} destinations, ${GUIDES.length} guides`);
