/**
 * The MVP live-status sheet — what is LIVE, what is PREVIEW, and how deep.
 *
 * David asked for it in his 2026-09-07 website notes (⑥): "You will need an
 * instruction sheet or something that details what our MVP has live etc." The
 * audience is David walking a VC through the site — so it answers, per surface,
 * the question a demo raises: is this bookable now, visible-but-coming, or a
 * socket? Every number is read from the same source files the site renders
 * from, because a status sheet with a typed count is how a pitch says "10
 * categories, 35 interests" over a page showing something else.
 *
 * Run:  npm run gen:status   → docs/mvp-live-status.md
 * Guarded by check:generated like every other generated artifact.
 */
import { writeGenerated } from "./lib/write-generated";
import { SIS, boardSis, SI_GROUPS, WELLS, LUX_WELLS, REGIONS, LOCALES } from "../src/data/taxonomy";
// places-merged, NOT places: the bundle carries only the 44 fallback rows,
// while the site (DB + prerender) serves the full merged catalog including
// every dropped-in dossier. A status sheet counting the fallback would
// understate the product by ~90%.
import { DESTINATIONS, PROVIDERS, GUIDES } from "./ssr/places-merged";
import { MESSAGES } from "../src/lib/i18n";
import SAFETY from "../src/data/safety.json";

const stamp = new Date().toISOString().slice(0, 10);

const BOARD = boardSis(SIS) as typeof SIS;
const liveSis = BOARD.filter((s) => s.status === "live");
const allDests = Object.values(DESTINATIONS).flat();
const liveDests = allDests.filter((d) => d.status === "live");
const allProviders = Object.values(PROVIDERS).flat();
const providerNames = new Set(allProviders.map((p) => p.name));
const allWells = [...WELLS, ...LUX_WELLS];
const liveWells = allWells.filter((w) => w.status === "live");

/** Live destinations carrying an interest — the "shelf" behind a live SI.
 *  A live interest with an empty shelf is the ski case: status live by
 *  decision, content ingest-then-flip (see status-and-launch-plan). */
const shelf = (siId: string) => liveDests.filter((d) => (d.si ?? []).includes(siId)).length;

/** Per-locale translation coverage of the UI string catalog. */
const localeCoverage = (code: string) =>
  Object.values(MESSAGES).filter((entry) => (entry as Record<string, string | undefined>)[code]).length;
const totalKeys = Object.keys(MESSAGES).length;

const zoneCount = Object.values(SAFETY as Record<string, { zones?: unknown[] }>).reduce(
  (n, c) => n + (c.zones?.length ?? 0), 0);

const destByRegion = (code: string) => {
  const rows = DESTINATIONS[code] ?? [];
  return { live: rows.filter((d) => d.status === "live").length, total: rows.length };
};

const depthCount = (depth: string) => liveDests.filter((d) => d.depth === depth).length;

const siRow = (s: (typeof SIS)[number]) => {
  if (s.status === "live") {
    const n = shelf(s.id);
    const note = n === 0 ? " — **live, shelf empty (ingest-then-flip)**" : ` — ${n} live destination${n === 1 ? "" : "s"} on the shelf`;
    return `| ${s.name} | \`${s.id}\` | **LIVE**${note} |`;
  }
  return `| ${s.name} | \`${s.id}\` | preview (visible, marked "soon", not bookable) |`;
};

const md = `# TravelWell.World MVP — live-status sheet

*Generated by \`scripts/gen-mvp-status.ts\` (\`npm run gen:status\`) from the same
source files the site renders. Content last changed ${stamp}. Do not hand-edit —
regenerate.*

The vocabulary, once: **LIVE** means on the site and functional today.
**Preview / soon** means visible on the site, labelled as coming, not bookable.
A **socket** is a seam poured in the foundation for machinery that is
deliberately not built yet (see CLAUDE.md "Foundation sockets").

## At a glance

| Surface | Published | Live today |
|---|---|---|
| Signature Interests (the Board) | **${BOARD.length}** in **${SI_GROUPS.length}** categories | **${liveSis.length}** live, ${BOARD.length - liveSis.length} preview |
| Wells | **${allWells.length}** (the full roster is the published count) | ${liveWells.length} live, ${allWells.length - liveWells.length} marked soon |
| Regions | **${REGIONS.length}** (the official 13-code scheme) | ${REGIONS.filter((r) => r.status === "live").length} live |
| Destinations | **${allDests.length}** rows | ${liveDests.length} live (${depthCount("verified")} verified · ${depthCount("stub")} stub · ${depthCount("cached")} cached) |
| Providers | **${providerNames.size}** across ${Object.keys(PROVIDERS).length} Wells | all seeded; booking is handoff/affiliate — see Payments below |
| Travel guides | **${GUIDES.length}** editorial guides | all live |
| Languages | **${LOCALES.length}** on the switcher | ${LOCALES.filter((l) => localeCoverage(l.code) > 0).length} fully translated (see Languages) |
| Safety records | **${Object.keys(SAFETY).length}** countries, ${zoneCount} named zones | advisory checker runs daily |

## The Board — ${BOARD.length} Signature Interests, ${SI_GROUPS.length} categories (David-locked 2026-08-10)

A **live** interest is bookable through its page today. A live interest with an
**empty shelf** is live by decision with content arriving (ingest-then-flip —
the ski pattern). **Preview** interests render a full page marked "soon".

${SI_GROUPS.map((g) => {
  const items = BOARD.filter((s) => s.group === g.id);
  const liveN = items.filter((s) => s.status === "live").length;
  return `### ${g.name} (${items.length} — ${liveN} live)

| Interest | id | Status |
|---|---|---|
${items.map(siRow).join("\n")}`;
}).join("\n\n")}

## The 13 Wells (David-locked 2026-08-10: "THE 13 WELLS")

The published count is always the full roster of ${allWells.length}; the Wells page marks
the not-yet-live ones "Soon".

| Well | Status | Tier |
|---|---|---|
${allWells.map((w) => `| ${w.name} | ${w.status === "live" ? "**LIVE**" : "soon"} | ${w.lux ? "luxury" : "core"} |`).join("\n")}

## Regions — the official 13-code scheme

| Code | Region | Status | Destinations (live / total rows) |
|---|---|---|---|
${REGIONS.map((r) => { const c = destByRegion(r.code); return `| \`${r.code}\` | ${r.name} | ${r.status === "live" ? "**LIVE**" : r.status} | ${c.live} / ${c.total} |`; }).join("\n")}

Destination depth (live rows): **${depthCount("verified")} verified** (full dossier),
**${depthCount("stub")} stub** (shown but thin), **${depthCount("cached")} cached**.

## Languages — ${LOCALES.length} on the switcher

"Fully translated" = every one of the ${totalKeys} interface strings plus the catalog
names. Anything untranslated falls back to English rather than breaking, so
languages can go live one at a time. Well names and the slogan family stay
English in every market by David's lock (a coined brand is not translated).

| Language | Code | Direction | Menu tier | Interface strings translated |
|---|---|---|---|---|
${LOCALES.map((l) => `| ${l.label} (${l.native}) | \`${l.code}\` | ${l.dir} | ${l.tier} | ${l.code === "en" ? `source (${totalKeys})` : `${localeCoverage(l.code)} of ${totalKeys}`} |`).join("\n")}

## The safety spine — live

- **${Object.keys(SAFETY).length} country records** with L1–L4 levels; **${zoneCount} named zones** carry their own
  level/posture structurally (never prose), with \`except\` carve-outs in both
  directions.
- **Advisory checker runs daily** (\`supabase/functions/advisory-check\`); any
  level move surfaces the same day, in either direction; nothing auto-publishes.
- **Emergency is network-free**: the panel renders 112 and local numbers with no
  connection, and the red Emergency control is in the sticky header on every
  page.
- Booking gates: L1/L2 book freely; L3 books only past all three safety gates;
  L4 and L3-blocked are content-only.

## Live by design decisions (so a demo answers the question before it's asked)

- **Payments:** TravelWell never touches the card at any tier — the provider is
  always merchant of record. This is Stage 1 of a staged plan, not a gap; the
  Stage 2 flip is a deliberate post-funding decision (see CLAUDE.md).
- **Atlas:** typed conversation and spoken dictation (Talk → Stop → Send) are
  live in the site's language; his replies can be read on every device. The
  real-time voice pipeline is spike-proven but its worker is not deployed —
  live voice runs only where that process is up.
- **Sign-in:** passwordless magic link. Delivery is on the default mailer until
  the branded SMTP (Resend) is verified — the templates are ready.
- **Sockets, poured and waiting** (not built, by decision): institutional/entity
  universes, split-group payments (a share is a state on a placed experience,
  never a payment record), the provider capability ledger's full watcher,
  per-locale URLs for nine-language SEO.

---
*Every figure above is computed from \`src/data\` and \`src/lib\` at generation
time. If this sheet disagrees with the site, regenerate it; if it still
disagrees, that is a bug worth filing.*
`;

const res = writeGenerated("docs/mvp-live-status.md", md, [/Content\nlast changed \d{4}-\d{2}-\d{2}/, /Content last changed \d{4}-\d{2}-\d{2}/]);
console.log(`docs/mvp-live-status.md — ${res}. ${BOARD.length} interests (${liveSis.length} live), ${allWells.length} Wells (${liveWells.length} live), ${allDests.length} destinations (${liveDests.length} live), ${providerNames.size} providers, ${LOCALES.length} locales.`);
