/**
 * Generate `supabase/functions/mcp/safety-fallback.ts` — the MCP server's
 * safety module — by bundling the REAL resolver (`src/data/safety-data.ts` +
 * `safety.json` + `advisory-sources.ts`) behind the thin agent-facing adapter
 * in `scripts/mcp-safety-src.ts`.
 *
 * WHY. The previous fallback was baked once from a June copy of safety.json by
 * a scratchpad script that no longer exists. Nothing regenerated it, nothing
 * checked it, and it drifted for ten weeks — retired authority, numeric
 * levels, and a fail-OPEN default for unknown countries, all still deployed.
 * A generated file whose generator lives in the repo and runs under
 * `check:generated` cannot repeat that: any edit to the safety data or the
 * resolver that is not re-bundled refuses the commit.
 *
 *   npm run gen:mcp-safety
 */
import { buildSync } from "esbuild";
import { writeGenerated, VOLATILE_DATE } from "./lib/write-generated";

const out = buildSync({
  entryPoints: ["scripts/mcp-safety-src.ts"],
  bundle: true,
  platform: "neutral",
  format: "esm",
  target: "es2022",
  write: false,
  define: { "import.meta.env": '{"DEV":false}' },
  legalComments: "none",
});

const code = out.outputFiles[0].text;

const header = `// AUTO-GENERATED by \`npm run gen:mcp-safety\` — do NOT hand-edit.
// Source: scripts/mcp-safety-src.ts, bundling src/data/safety-data.ts,
// src/data/safety.json and src/data/advisory-sources.ts. This is the SAME
// resolver the site runs (composite countries, zone joins, stricter-wins,
// fail-safe unverified) — regenerate rather than patching, or the MCP surface
// and the site disagree about safety, which is the failure this file replaced.
// Guarded by \`npm run check:generated\` (the pre-commit hook).

`;

const result = writeGenerated("supabase/functions/mcp/safety-fallback.ts", header + code, VOLATILE_DATE);
console.log(`supabase/functions/mcp/safety-fallback.ts ${result} (${((header.length + code.length) / 1024).toFixed(0)}KB bundled)`);
