/**
 * gen:manifest → docs/manifest.json
 *
 * THE ONE-FETCH STALENESS ANSWER (David, 2026-08-25: "Why are we looking at a
 * copy of her taxonomy? … What does it take to make that stop?").
 *
 * What it takes is making the fresh read CHEAPER than the stale note. Every
 * fact the research library consumes from this repo already lives in a
 * generated, gate-guarded file — the taxonomy in board.json, the counts and
 * vocabularies in ground-truth, the caps in list-sizes, the verified advisory
 * links, the slogan family. What was missing is the map: which file answers
 * which question, and a checksum that says in ONE fetch whether a cached copy
 * is still current.
 *
 * So this manifest lists every generated read surface with the question it
 * answers and the sha256 of its content. A consumer that caches any of these
 * files re-fetches ONLY the manifest (2 KB), compares hashes, and knows
 * exactly which of its copies died — no diffing, no guessing, no "measured at
 * a moving ref". A payload builder on the library side can stamp the hashes
 * it read into its output, and a report whose hashes no longer match the
 * manifest is stale BY MECHANICAL TEST, not by accusation.
 *
 * It regenerates with every commit (check:generated → the pre-commit hook),
 * so it cannot itself go stale without the gate refusing the commit.
 */
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { writeGenerated } from "./lib/write-generated";

const SURFACES: { file: string; answers: string }[] = [
  { file: "docs/board.json", answers: "THE BOARD — the 35 interests in David's locked order with Block A fields, the 4 retired slugs, the 13 Wells, categories, img tokens, wired sub-regions. The canonical slug set is interests[].id + retired[]." },
  { file: "docs/ground-truth.md", answers: "Every count, field path and vocabulary read from source with file:line, plus conformance checks. The fact sheet for reasoning about this repo without reading it." },
  { file: "docs/reset-facts.txt", answers: "The paste-block distillation of ground-truth for contexts that cannot fetch files." },
  { file: "docs/list-sizes.json", answers: "Every literal cap on a published surface vs the current length of the list it cuts — the cap-ratchet's runtime half." },
  { file: "docs/tagline-family.md", answers: "The documented slogan family in active use (regenerate before any filing)." },
  { file: "docs/advisory-links.md", answers: "The advisory deep links per served country, as the site emits them." },
  { file: "docs/advisory-countries.json", answers: "The daily checker's country payload — ISO, name, match strings, verified FCDO slug." },
  { file: "vercel.json", answers: "The live route table (rewrites generated from the router)." },
];

const rows = SURFACES.map(({ file, answers }) => {
  const body = readFileSync(file);
  return { file, answers, sha256: createHash("sha256").update(body).digest("hex"), bytes: body.length };
});

const doc = {
  _what: "Every generated read surface in this repo: which question it answers, and the sha256 of its current content. Fetch THIS file first; a cached copy whose hash no longer matches is stale by mechanical test.",
  _rule: "Never quote a fact about this repo from a note, a mirror, or a previous payload. Read the surface that answers it, and stamp the hash you read. One fetch of this manifest tells you which of your copies died.",
  _generated_by: "scripts/gen-manifest.ts — regenerated by check:generated on every commit, so it cannot itself go stale without the gate refusing the commit",
  generated: new Date().toISOString().slice(0, 10),
  surfaces: rows,
};

writeGenerated("docs/manifest.json", JSON.stringify(doc, null, 1) + "\n", [/"generated": "\d{4}-\d{2}-\d{2}"/]);
console.log(`docs/manifest.json — ${rows.length} read surfaces hashed.`);
