-- TravelWell.World — seed the Special Interests + Activities catalog.
--
-- GENERATED by scripts/gen-catalog-seed.ts from the bundled catalog (SIS +
-- ACTIVITIES, including David's special-interests.json). Do not hand-edit —
-- regenerate after catalog changes. Idempotent (ON CONFLICT DO UPDATE), so it
-- doubles as the refresh path and the next slice of catalog -> DB.
--
-- Apply:  supabase db push   (or paste into the Supabase SQL editor)
-- Requires 0001 (tables) and 0002 (wells, for the activities.well FK).

-- Special Interests -----------------------------------------------------------
insert into public.special_interests (id, name, signature, status, accent, is_lux, grp, data) values
  ('ultra', 'Ultra-Luxury', 'the extraordinary', 'live', '#A8873F', true, 'premium', null),
  ('tropical', 'Tropical Islands', 'barefoot luxury', 'live', '#2E8C8C', false, 'premium', null),
  ('romance', 'Romance, Marriages & Honeymoons', 'the two of you', 'live', '#A8527A', false, 'premium', null),
  ('safari', 'Safari Adventures', 'the wild calling', 'live', '#B07A3C', false, 'premium', null),
  ('expedition', 'Global Expedition Adventures', 'to the edges of the map', 'live', '#5C5C5C', false, 'premium', null),
  ('ski', 'Winter/Ski', 'the first track', 'live', '#5B86A8', false, 'premium', null),
  ('golf', 'Golf Globally', 'the round of your life', 'preview', '#2F6B3A', false, 'premium', null),
  ('rail', 'Global Rail Journeys', 'the long way, beautifully', 'preview', '#6B5B4F', false, 'journeys', null),
  ('barge', 'Hotel-Barge & Canal Cruising', 'six knots, no hurry', 'preview', '#4F7A8C', false, 'journeys', null),
  ('privatejet', 'Private-Jet Expeditions', 'the world in one arc', 'preview', '#8C7A4F', false, 'journeys', null),
  ('caravan', 'Desert & Camel Caravans', 'dunes at first light', 'preview', '#C08A4A', false, 'journeys', null),
  ('overland', 'Luxury Overland Expeditions', 'the road as the journey', 'preview', '#8A6234', false, 'journeys', null),
  ('motoring', 'Classic-Car & Motorcycle Touring', 'the open road, in something special', 'preview', '#9E3B2E', false, 'journeys', null),
  ('adventure', 'Global Adventures', 'the world, wide open', 'preview', '#3C7E55', false, 'adventure', null),
  ('hiking', 'Hiking & Trekking', 'the trail ahead', 'preview', '#4A8C5E', false, 'adventure', null),
  ('liveaboard', 'Dive Liveaboards', 'sleep above the reef', 'live', '#2E6E8C', false, 'water', null),
  ('river', 'River Cruises', 'the slow current', 'live', '#5B86A8', false, 'water', null),
  ('diveglobal', 'Dive Globally', 'the world below', 'preview', '#1F6E8C', false, 'water', null),
  ('ocean', 'Ocean & Watersports', 'the open water', 'preview', '#2C6E68', false, 'water', null),
  ('wellness', 'Wellness, Spa & Retreats', 'coming home to yourself', 'preview', '#4F8C7A', false, 'nature', null),
  ('wildlife', 'Wildlife & Nature', 'wild places, up close', 'preview', '#4A7A3C', false, 'nature', null),
  ('glamping', 'Global Glamping', 'wild, but well-appointed', 'preview', '#7A6B4F', false, 'adventure', null),
  ('family', 'Family Travel', 'everyone, together', 'preview', '#C98A2E', false, 'lifestage', null),
  ('group', 'Group Travel', 'better, together', 'preview', '#C27A3C', false, 'lifestage', null),
  ('senior', 'Senior Travel', 'unhurried, well-earned', 'preview', '#7A5B3B', false, 'lifestage', null),
  ('culture', 'Culture & Heritage', 'the soul of a place', 'preview', '#7A5BA8', false, 'culture', null),
  ('deepdive', 'Cultural Deep Dives', 'beneath the surface', 'preview', '#6B4F9E', false, 'culture', null),
  ('pilgrimage', 'Religious & Pilgrimage', 'the road as devotion', 'preview', '#8C6B4F', false, 'culture', null),
  ('entertainment', 'Global Live Entertainment', 'the lights come up', 'preview', '#C2562E', false, 'entertainment', null),
  ('culinary', 'Culinary Experiences', 'a table worth the flight', 'preview', '#9C5B3B', false, 'culinary', null),
  ('sports', 'Individual Sports', 'your sport, somewhere new', 'preview', '#3C7E55', false, 'sports', null),
  ('spectator', 'Sports Spectator Travel', 'from the stands', 'preview', '#2C6E68', false, 'sports', null),
  ('nightlife', 'Nightlife & City', 'the city after dark', 'preview', '#3C3C5C', false, 'culture', null),
  ('olympic', 'Olympic Travel', 'the world’s stage', 'preview', '#C2562E', false, 'sports', null),
  ('prosports', 'Pro Sports Team Travel', 'follow the pros', 'preview', '#B07A3C', false, 'sports', null),
  ('compsports', 'Competitive Sports Team Travel', 'travel to compete', 'preview', '#2E6E8C', false, 'sports', null),
  ('sailing', 'Sailing Charters', 'wind in your favor', 'preview', '#2E6E8C', false, 'water', null),
  ('yacht', 'Yacht Charters', 'the open sea, served well', 'preview', '#1F5C73', true, 'water', null),
  ('wine', 'Wine & Whiskey/Spirits Tours', 'the world, one glass at a time', 'preview', '#7B3F52', false, 'culinary', null)
on conflict (id) do update set
  name = excluded.name, signature = excluded.signature, status = excluded.status,
  accent = excluded.accent, is_lux = excluded.is_lux, grp = excluded.grp, data = excluded.data;

-- Self-clean, same discipline as the destinations seed: an SI RETIRED in
-- src/data/taxonomy.ts must also leave the DB. Without this the seed was
-- insert-and-upsert only, so a removed interest would linger in Postgres and —
-- because the app reads DB-first with the bundle only as fallback — keep showing
-- in production after it had been deleted from the source. Silent and confusing.
delete from public.special_interests where id not in ('ultra', 'tropical', 'romance', 'safari', 'expedition', 'ski', 'golf', 'rail', 'barge', 'privatejet', 'caravan', 'overland', 'motoring', 'adventure', 'hiking', 'liveaboard', 'river', 'diveglobal', 'ocean', 'wellness', 'wildlife', 'glamping', 'family', 'group', 'senior', 'culture', 'deepdive', 'pilgrimage', 'entertainment', 'culinary', 'sports', 'spectator', 'nightlife', 'olympic', 'prosports', 'compsports', 'sailing', 'yacht', 'wine');

-- Activities ------------------------------------------------------------------
-- Laddered experiences per Special Interest. si_id is a plain key (not all
-- activity groups map to a canonical SI in the prototype); well FKs to wells.
create table if not exists public.activities (
  si_id     text not null,
  id        text not null,
  name      text not null,
  well      text not null references public.wells(id),
  line      text,
  position  int not null default 0,
  primary key (si_id, id)
);

alter table public.activities enable row level security;
do $$
begin
  create policy "read activities" on public.activities for select using (true);
exception when duplicate_object then null;
end $$;

insert into public.activities (si_id, id, name, well, line, position) values
  ('safari', 'game-drive', 'Dawn game drives', 'activities', 'Golden-hour with a private guide', 0),
  ('safari', 'balloon', 'Hot-air balloon safari', 'activities', 'Float over the herds at sunrise', 1),
  ('safari', 'tented-camp', 'Luxury tented camp', 'stay', 'Canvas suites, no walls between you and the wild', 2),
  ('safari', 'bush-dinner', 'Bush dinner under the stars', 'eat', 'A candlelit table on the plains', 3),
  ('safari', 'walking-safari', 'Guided walking safari', 'activities', 'Track on foot with an armed ranger', 4),
  ('safari', 'conservancy', 'Conservancy & community visit', 'activities', 'Travel that gives back', 5),
  ('romance', 'private-dinner', 'Private sunset dinner', 'eat', 'Just the two of you, somewhere unforgettable', 0),
  ('romance', 'couples-spa', 'Couples spa ritual', 'beauty', 'Side-by-side, unhurried', 1),
  ('romance', 'honeymoon-suite', 'Boutique honeymoon suite', 'stay', 'A room you won''t want to leave', 2),
  ('romance', 'sunset-cruise', 'Sunset cruise', 'activities', 'Champagne on calm water', 3),
  ('romance', 'photo-session', 'Keepsake photo session', 'activities', 'A pro to capture the trip', 4),
  ('culinary', 'chefs-table', 'Chef''s table tasting menu', 'eat', 'The best seat in the house', 0),
  ('culinary', 'market-tour', 'Local market food tour', 'activities', 'Eat where the locals eat', 1),
  ('culinary', 'cooking-class', 'Hands-on cooking class', 'activities', 'Take the flavors home', 2),
  ('culinary', 'wine-pairing', 'Wine-paired dinner', 'eat', 'Every course, perfectly matched', 3),
  ('culinary', 'street-food', 'Street-food crawl', 'eat', 'The soul of a city, one stall at a time', 4),
  ('ocean', 'snorkel', 'Reef snorkeling trip', 'activities', 'Into the world below', 0),
  ('ocean', 'beach-resort', 'Beachfront resort', 'stay', 'Wake up to the water', 1),
  ('ocean', 'sail', 'Sunset sail', 'activities', 'Wind in your favor', 2),
  ('ocean', 'seafood', 'Fresh seafood feast', 'eat', 'Off the boat, onto the plate', 3),
  ('wellness', 'spa-day', 'Signature spa day', 'beauty', 'Come home to yourself', 0),
  ('wellness', 'yoga-retreat', 'Sunrise yoga & meditation', 'activities', 'Begin slow, breathe deep', 1),
  ('wellness', 'wellness-resort', 'Wellness resort stay', 'stay', 'Built around your rest', 2),
  ('wellness', 'clean-dining', 'Nourishing clean dining', 'eat', 'Food that loves you back', 3),
  ('culture', 'guided-old-town', 'Guided old-town walk', 'activities', 'The soul of a place, on foot', 0),
  ('culture', 'artisan', 'Artisan workshop visit', 'activities', 'Meet the makers', 1),
  ('culture', 'heritage-stay', 'Heritage boutique stay', 'stay', 'Sleep inside the history', 2),
  ('culture', 'local-feast', 'Family-table local feast', 'eat', 'A meal that tells a story', 3),
  ('adventure', 'trek', 'Multi-day guided trek', 'activities', 'The trail ahead', 0),
  ('adventure', 'summit', 'Summit attempt', 'activities', 'Earn the view', 1),
  ('adventure', 'mountain-lodge', 'Mountain lodge stay', 'stay', 'Boots off, fire on', 2),
  ('adventure', 'gear-up', 'Expedition gear fitting', 'gear', 'What you carry matters', 3),
  ('family', 'kid-safari', 'Kid-friendly wildlife day', 'activities', 'Wonder for every age', 0),
  ('family', 'family-suite', 'Family suite or villa', 'stay', 'Room for everyone, together', 1),
  ('family', 'easy-eats', 'Relaxed family dining', 'eat', 'Happy kids, happy table', 2),
  ('family', 'nanny', 'Trusted local nanny', 'nanny', 'An afternoon just for the grown-ups', 3),
  ('ultra', 'private-villa', 'Private villa with staff', 'stay', 'Discreet, effortless, yours', 0),
  ('ultra', 'private-jet', 'Private jet transfer', 'fly', 'Skip every line', 1),
  ('ultra', 'michelin', 'In-villa Michelin chef', 'eat', 'The restaurant comes to you', 2),
  ('ultra', 'security', 'Discreet close protection', 'security', 'Peace of mind, unseen', 3),
  ('ultra', 'curator', 'Personal experience curator', 'activities', 'Doors that don''t open for others', 4),
  ('solo', 'small-group', 'Small-group day tour', 'activities', 'Company when you want it', 0),
  ('solo', 'safe-stay', 'Vetted central stay', 'stay', 'Safe, social, well-placed', 1),
  ('solo', 'communal-table', 'Communal chef''s table', 'eat', 'Make friends over dinner', 2),
  ('sailing', 'skippered-charter', 'Skippered day charter', 'activities', 'Out for the day with a skipper at the helm', 0),
  ('sailing', 'bareboat-sailing', 'Bareboat charter', 'move', 'Captain your own sailboat, the freedom of the wind', 1),
  ('sailing', 'crewed-sailing', 'Crewed sailing yacht', 'move', 'Your own yacht and crew for the week', 2),
  ('sailing', 'flotilla', 'Flotilla sailing', 'activities', 'Island-hop in a small, friendly fleet', 3),
  ('sailing', 'sailing-school', 'Sailing school', 'activities', 'Learn to sail with certified instructors', 4),
  ('sailing', 'marina-stay', 'Marina-side stay', 'stay', 'Wake up on the water, dock to dock', 5),
  ('yacht', 'superyacht-charter', 'Superyacht charter', 'move', 'A superyacht and full crew, nothing held back', 0),
  ('yacht', 'crewed-motor-yacht', 'Crewed motor yacht', 'move', 'Captain, crew, and the run of the coast', 1),
  ('yacht', 'day-motor-charter', 'Day motor charter', 'move', 'A day on the water, captain included', 2),
  ('yacht', 'marina-berth', 'Marina berth & stay', 'stay', 'Step off the deck into the harbor town', 3),
  ('wine', 'wine-country-tour', 'Wine country tour', 'activities', 'Vineyard tastings from Napa to Bordeaux to Mendoza', 0),
  ('wine', 'whisky-trail', 'Whisky & whiskey trail', 'activities', 'Scotch and Irish whiskey trails with the makers', 1),
  ('wine', 'world-distilleries', 'World distilleries', 'activities', 'Japanese whisky, rum, tequila and cognac journeys', 2),
  ('wine', 'harvest-experience', 'Harvest experience', 'activities', 'Hands in the harvest - crush, blend, foot-tread', 3),
  ('wine', 'vineyard-estate-stay', 'Vineyard estate stay', 'stay', 'Sleep among the vines', 4),
  ('wine', 'rum-and-sail', 'Rum & sail', 'activities', 'Caribbean distillery tour plus a sunset sail', 5)
on conflict (si_id, id) do update set
  name = excluded.name, well = excluded.well, line = excluded.line, position = excluded.position;
