-- TravelWell.World — seed Providers + Sub-regions.
--
-- GENERATED by scripts/gen-catalog-seed.ts from the bundled catalog (PROVIDERS
-- in places.ts + SUBREGIONS in taxonomy.ts). Do not hand-edit — regenerate
-- after catalog changes. Idempotent (ON CONFLICT DO UPDATE).
--
-- Apply:  supabase db push   (or paste into the Supabase SQL editor)
-- Requires 0001 (providers table + RLS) and 0002 (wells/regions, for the FKs).

-- Providers -------------------------------------------------------------------
-- The providers table (0001) has a generated uuid pk; add a natural key so the
-- seed is idempotent and can act as the refresh path.
create unique index if not exists providers_name_well_key on public.providers (name, well);

-- Step 1 of the matching keystone: give providers an SI dimension and a region
-- dimension, so the catalog can express "Caribbean dive providers". Additive —
-- matching that reads these lands in a later step.
alter table public.providers add column if not exists si          text[] not null default '{}';
alter table public.providers add column if not exists region      text;
alter table public.providers add column if not exists booking_url text;
-- One description cannot serve six SI doors: a provider surfaces on every interest
-- it serves, and the sentence a traveller reads should answer the door they came
-- through. Additive and nullable: a row that fills none of it renders description.
alter table public.providers add column if not exists desc_by_si jsonb;
create index if not exists providers_region_idx on public.providers (region);

insert into public.providers (name, well, tier, price, mode, description, commission, si, region, booking_url, desc_by_si) values
  ('Angama Mara', 'stay', 'prime', 'ultra', 'api', 'Clifftop tented suites with sweeping Mara views', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Governors'' Camp', 'stay', 'prime', 'premier', 'api', 'Front-row tents on the Mara River', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Mahali Mzuri', 'stay', 'prime', 'ultra', 'widget', 'Sir Richard Branson''s tented camp', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Sarova Mara Game Camp', 'stay', 'vetted', 'comfort', 'api', 'Reliable comfort in the heart of the reserve', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Fairmont Mara Safari Club', 'stay', 'vetted', 'premier', 'widget', 'Luxury tents in a river bend', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Mara Serena Safari Lodge', 'stay', 'vetted', 'comfort', 'api', 'Hilltop lodge, panoramic plains', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Basecamp Explorer', 'stay', 'vetted', 'essential', 'affiliate', 'Eco-camp with community roots', 'Affiliate partner', '{"safari"}', '05A', null, null),
  ('Entim Mara Camp', 'stay', 'prospective', 'comfort', 'affiliate', 'Riverside camp near crossing points', 'Prospective partner', '{"safari"}', '05A', null, null),
  ('Backstage Hotel Zermatt', 'stay', 'prime', 'luxury', 'affiliate', 'Design boutique in car-free Zermatt, minutes from the Matterhorn lifts', 'Commission partner', '{"ski","wellness"}', '01F', null, null),
  ('Hotel Arlberg St. Anton', 'stay', 'prime', 'premier', 'affiliate', 'Family-run five-star ski-in ski-out on the Arlberg', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Hôtel Mont-Blanc Chamonix', 'stay', 'vetted', 'premier', 'affiliate', 'Historic grande-dame in central Chamonix with Mont Blanc views', 'Commission partner', '{"ski","adventure"}', '01F', null, null),
  ('Badrutt''s Palace Hotel, St. Moritz', 'stay', 'prime', 'ultra', 'affiliate', 'The landmark of St. Moritz since 1896 — grande-dame luxury above the frozen lake', 'Commission partner', '{"ski","wellness"}', '01F', null, null),
  ('Cheval Blanc Courchevel', 'stay', 'prime', 'ultra', 'affiliate', 'LVMH''s ski-in maison at Courchevel 1850 — the height of the Trois Vallées', 'Commission partner', '{"ski","wellness"}', '01F', null, null),
  ('Cristallo, a Luxury Collection Resort, Cortina', 'stay', 'prime', 'luxury', 'affiliate', 'Belle-époque grande-dame with Dolomite views and a Roman-style spa', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Tennerhof Gourmet & Spa Hotel, Kitzbühel', 'stay', 'prime', 'luxury', 'affiliate', 'Relais & Châteaux chalet above the medieval town', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Kenya Airways', 'fly', 'prime', 'comfort', 'api', 'Direct into Nairobi (NBO)', 'Commission partner', '{"safari"}', '05A', null, null),
  ('SafariLink', 'fly', 'prime', 'comfort', 'api', 'Light-aircraft hops to the Mara airstrips', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Qatar Airways', 'fly', 'vetted', 'premier', 'widget', 'One-stop via Doha, award cabins', 'Commission partner', '{"safari"}', '05A', null, null),
  ('AirKenya Express', 'fly', 'vetted', 'comfort', 'api', 'Scheduled bush flights', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Emirates', 'fly', 'vetted', 'premier', 'widget', 'One-stop via Dubai', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Skyward Private Jets', 'fly', 'prospective', 'ultra', 'affiliate', 'Charter direct to camp', 'Prospective partner', '{"safari"}', '05A', null, null),
  ('Bush Dinner by Angama', 'eat', 'prime', 'premier', 'api', 'Candlelit dining on the plains', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Emakoko Restaurant', 'eat', 'vetted', 'comfort', 'api', 'Farm-to-table at the park gate', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Talisman, Nairobi', 'eat', 'vetted', 'comfort', 'affiliate', 'A Karen institution before you fly out', 'Affiliate partner', '{"safari"}', '05A', null, null),
  ('Carnivore Nairobi', 'eat', 'vetted', 'essential', 'affiliate', 'The famous beast-of-a-feast', 'Affiliate partner', '{"safari"}', '05A', null, null),
  ('Private Chef — Mara', 'eat', 'prospective', 'premier', 'affiliate', 'In-camp tasting menus', 'Prospective partner', '{"safari"}', '05A', null, null),
  ('Chez Vrony, Zermatt', 'eat', 'prime', 'premier', 'affiliate', 'Iconic mountainside restaurant above Zermatt — a Matterhorn table', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Chesa Veglia, St. Moritz', 'eat', 'prime', 'luxury', 'affiliate', 'Badrutt''s 1658 farmhouse — grill, pizza and old-world Engadin glamour', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Le Chabichou, Courchevel', 'eat', 'prime', 'luxury', 'affiliate', 'Two-Michelin-star Savoyard cooking on the piste at 1850', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Rifugio Averau, Cortina', 'eat', 'vetted', 'premier', 'affiliate', 'Storied mountain hut on the Cinque Torri — Dolomite classics with a view', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Mara Land Cruiser Safaris', 'move', 'prime', 'comfort', 'api', 'Private 4×4 with expert guide', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Abercrombie & Kent Transfers', 'move', 'prime', 'premier', 'widget', 'Seamless private transfers', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Scenic Air Transfers', 'move', 'vetted', 'premier', 'api', 'Fly between camps', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Nairobi Executive Cars', 'move', 'vetted', 'comfort', 'affiliate', 'Airport & city transfers', 'Affiliate partner', '{"safari"}', '05A', null, null),
  ('Self-Drive Kenya', 'move', 'prospective', 'essential', 'affiliate', 'For the independent traveler', 'Prospective partner', '{"safari"}', '05A', null, null),
  ('Alpybus Alpine Transfers', 'move', 'vetted', 'comfort', 'affiliate', 'Shared & private transfers from Geneva/Zurich to the Alps resorts', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Safari Outfitters Co.', 'gear', 'prime', 'comfort', 'affiliate', 'Boots, layers, dry-bags — delivered', 'Affiliate partner', '{"safari"}', '05A', null, null),
  ('Optics & Binoculars Rental', 'gear', 'vetted', 'essential', 'affiliate', 'Pro glass for game viewing', 'Affiliate partner', '{"safari"}', '05A', null, null),
  ('TravelWell Gear Edit', 'gear', 'vetted', 'comfort', 'api', 'Our curated safari packing list', 'First-party', '{"safari"}', '05A', null, null),
  ('Angama Spa', 'beauty', 'prime', 'premier', 'api', 'Treatments with a view', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Sundowner Wellness', 'beauty', 'vetted', 'comfort', 'affiliate', 'Massage & recovery in-camp', 'Affiliate partner', '{"safari"}', '05A', null, null),
  ('Mara Hot-Air Balloon', 'activities', 'prime', 'premier', 'api', 'Sunrise flight + champagne breakfast', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Maasai Village Cultural Visit', 'activities', 'prime', 'essential', 'api', 'Meet the community, respectfully', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Big Cat Tracking Experience', 'activities', 'vetted', 'premier', 'widget', 'With a resident researcher', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Walking Safari — Olare Motorogi', 'activities', 'vetted', 'comfort', 'api', 'On foot with armed rangers', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Photography Safari Workshop', 'activities', 'vetted', 'premier', 'affiliate', 'Pro tuition in the field', 'Affiliate partner', '{"safari"}', '05A', null, null),
  ('Night Game Drive', 'activities', 'prospective', 'comfort', 'affiliate', 'Spot the nocturnal Mara', 'Prospective partner', '{"safari"}', '05A', null, null),
  ('Zermatters Ski & Guide School', 'activities', 'prime', 'premier', 'affiliate', 'Zermatt''s official ski school & mountain-guide bureau — lessons, off-piste, touring', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Compagnie des Guides de Chamonix', 'activities', 'prime', 'premier', 'affiliate', 'The world''s oldest guide company (1821) — Vallée Blanche, off-piste, alpinism', 'Commission partner', '{"ski","adventure"}', '01F', null, null),
  ('Arlberg Ski School, St. Anton', 'activities', 'vetted', 'comfort', 'affiliate', 'The historic Arlberg school — the technique that founded the sport', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Schweizer Skischule St. Moritz', 'activities', 'prime', 'premier', 'affiliate', 'St. Moritz''s official Swiss ski school — lessons, off-piste and Engadin touring', 'Commission partner', '{"ski"}', '01F', null, null),
  ('ESF Courchevel', 'activities', 'vetted', 'comfort', 'affiliate', 'École du Ski Français — lessons and guiding across the Trois Vallées', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Scuola Sci Cortina', 'activities', 'vetted', 'comfort', 'affiliate', 'Cortina''s historic ski school — Dolomiti Superski lessons and guided off-piste', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Rote Teufel Ski School, Kitzbühel', 'activities', 'prime', 'premier', 'affiliate', 'The ''Red Devils'' — Kitzbühel''s legendary ski school since 1926', 'Commission partner', '{"ski"}', '01F', null, null),
  ('Maasai Market Curated', 'shop', 'vetted', 'essential', 'affiliate', 'Authentic crafts, fair trade', 'Affiliate partner', '{"safari"}', '05A', null, null),
  ('Utamaduni Craft Centre', 'shop', 'vetted', 'comfort', 'affiliate', 'Quality keepsakes near Nairobi', 'Affiliate partner', '{"safari"}', '05A', null, null),
  ('Mara Family Nannies', 'nanny', 'vetted', 'premier', 'api', 'Vetted, multilingual childcare in-camp', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Discreet Protection Kenya', 'security', 'vetted', 'ultra', 'api', 'Close protection, unseen', 'Commission partner', '{"safari"}', '05A', null, null),
  ('Bedsonline', 'stay', 'prime', 'comfort', 'api', 'Trade wholesaler for Caribbean hotels, transfers and activities — the commissionable backbone across the region', 'Commission partner', '{"tropical","romance","ocean"}', '11C', 'https://www.bedsonline.com', null),
  ('Grace Bay Club', 'stay', 'prime', 'luxury', 'affiliate', 'Original boutique resort on the world-ranked Grace Bay Beach, Providenciales', 'Commission partner', '{"tropical","romance"}', '11C', 'https://www.gracebayresorts.com/grace-bay-club', null),
  ('Amanyara', 'stay', 'prime', 'ultra', 'affiliate', 'Secluded Aman resort of 40 pavilions on the wild northwest shore of Providenciales', 'Commission partner', '{"tropical","romance","wellness"}', '11C', 'https://www.aman.com/resorts/amanyara', null),
  ('Beaches Turks & Caicos', 'stay', 'prime', 'premier', 'affiliate', 'Polished family all-inclusive on Grace Bay with waterpark and multiple villages', 'Commission partner', '{"tropical"}', '11C', 'https://www.beaches.com/resorts/turks-caicos', null),
  ('Sandals Royal Bahamian', 'stay', 'prime', 'premier', 'affiliate', 'Adults-only all-inclusive on Cable Beach, Nassau, with offshore island', 'Commission partner', '{"tropical","romance"}', '11C', 'https://www.sandals.com/royal-bahamian', null),
  ('The Cove Eleuthera', 'stay', 'vetted', 'luxury', 'affiliate', 'Boutique cliffside resort on a peninsula between two Eleuthera beaches', 'Commission partner', '{"tropical","romance"}', '11C', 'https://www.thecoveeleuthera.com', null),
  ('Jade Mountain', 'stay', 'prime', 'ultra', 'affiliate', 'Open-wall sanctuaries facing the Pitons, St. Lucia — a honeymoon icon', 'Commission partner', '{"romance","tropical","wellness"}', '11C', 'https://www.jademountain.com', null),
  ('Eden Rock St Barths', 'stay', 'prime', 'ultra', 'affiliate', 'Landmark luxury hotel on St. Jean Bay, St. Barthélemy', 'Commission partner', '{"tropical","romance"}', '11C', 'https://www.oetkercollection.com/hotels/eden-rock-st-barths', null),
  ('Hotel Christopher St Barth', 'stay', 'vetted', 'luxury', 'affiliate', 'Calm clifftop retreat with a large pool, Pointe Milou, St. Barthélemy', 'Commission partner', '{"tropical","romance"}', '11C', 'https://www.hotelchristopher.com', null),
  ('Spice Island Beach Resort', 'stay', 'prime', 'luxury', 'affiliate', 'All-inclusive on Grand Anse Beach, Grenada — family-owned, AAA Five Diamond', 'Commission partner', '{"tropical","romance"}', '11C', 'https://www.spiceislandbeachresort.com', null),
  ('Curtain Bluff', 'stay', 'prime', 'luxury', 'affiliate', 'Classic all-inclusive on two beaches, Antigua — sailing and watersports included', 'Commission partner', '{"tropical","romance","ocean"}', '11C', 'https://www.curtainbluff.com', null),
  ('Cap Juluca', 'stay', 'prime', 'ultra', 'affiliate', 'Belmond beachfront resort on Maundays Bay, Anguilla — Moorish-style luxury', 'Commission partner', '{"tropical","romance"}', '11C', 'https://www.belmond.com/hotels/caribbean/anguilla/belmond-cap-juluca', null),
  ('Bucuti & Tara Beach Resort', 'stay', 'prime', 'premier', 'affiliate', 'Adults-only eco-resort on Eagle Beach, Aruba — outside the hurricane belt', 'Commission partner', '{"tropical","romance","wellness"}', '11C', 'https://www.bucuti.com', null),
  ('Hotel Riu Palace Aruba', 'stay', 'vetted', 'comfort', 'affiliate', 'Large all-inclusive on Palm Beach, Aruba — reliable value with calm swimming water', 'Commission partner', '{"tropical"}', '11C', 'https://www.riu.com', null),
  ('The Crane Resort', 'stay', 'vetted', 'premier', 'affiliate', 'Historic clifftop resort above pink-sand Crane Beach, Barbados', 'Commission partner', '{"tropical","romance"}', '11C', 'https://www.thecrane.com', null),
  ('De Palm Tours', 'activities', 'vetted', 'comfort', 'affiliate', 'Aruba''s largest destination-management company — island tours, snorkel cruises, transfers', 'Commission partner', '{"tropical","ocean"}', '11C', 'https://www.depalmtours.com', null),
  ('Big Blue Collective', 'activities', 'prime', 'premier', 'affiliate', 'Eco-tour operator in Providenciales — snorkel, kayak, paddleboard, island ecotours', 'Commission partner', '{"ocean","tropical"}', '11C', 'https://www.bigbluecollective.com', null),
  ('Island Routes Caribbean Adventures', 'activities', 'vetted', 'comfort', 'affiliate', 'Regional tour operator across the Caribbean — vetted excursions and transfers', 'Commission partner', '{"tropical","ocean"}', '11C', 'https://www.islandroutes.com', null),
  ('Viator', 'activities', 'prospective', 'comfort', 'affiliate', 'Global activity marketplace — fallback booking for Caribbean tours and excursions', 'Affiliate partner', '{"tropical","ocean"}', '11C', 'https://www.viator.com', null),
  ('GetYourGuide', 'activities', 'prospective', 'comfort', 'affiliate', 'Global activity marketplace — Caribbean tours, day trips and tickets', 'Affiliate partner', '{"tropical","ocean"}', '11C', 'https://www.getyourguide.com', null),
  ('American Airlines', 'fly', 'vetted', 'comfort', 'affiliate', 'Major US carrier with broad nonstop service to Caribbean gateways', 'Affiliate partner', '{"tropical","romance","ocean"}', null, 'https://www.aa.com', null),
  ('JetBlue', 'fly', 'vetted', 'comfort', 'affiliate', 'US carrier with extensive Caribbean nonstop routes from East Coast hubs', 'Affiliate partner', '{"tropical","romance","ocean"}', null, 'https://www.jetblue.com', null),
  ('Delta Air Lines', 'fly', 'vetted', 'comfort', 'affiliate', 'Major US carrier serving principal Caribbean airports', 'Affiliate partner', '{"tropical","romance","ocean"}', null, 'https://www.delta.com', null)
on conflict (name, well) do update set
  tier = excluded.tier, price = excluded.price, mode = excluded.mode,
  description = excluded.description, commission = excluded.commission,
  si = excluded.si, region = excluded.region, booking_url = excluded.booking_url,
  desc_by_si = excluded.desc_by_si;

-- Sub-regions -----------------------------------------------------------------
create table if not exists public.sub_regions (
  region_code text not null references public.regions(code) on delete cascade,
  name        text not null,
  position    int not null default 0,
  primary key (region_code, name)
);

alter table public.sub_regions enable row level security;
do $$
begin
  create policy "read sub_regions" on public.sub_regions for select using (true);
exception when duplicate_object then null;
end $$;

insert into public.sub_regions (region_code, name, position) values
  ('04A', 'Egypt & the Nile', 0),
  ('04A', 'The Red Sea', 1),
  ('04A', 'Morocco', 2),
  ('04A', 'The Maghreb', 3),
  ('04A', 'Jordan & the Levant', 4),
  ('04A', 'The Gulf', 5),
  ('04A', 'Oman', 6),
  ('04A', 'Israel & the Holy Land', 7),
  ('04A', 'Saudi Arabia', 8),
  ('12A', 'Pacific Coast', 0),
  ('12A', 'Pacific Northwest', 1),
  ('12A', 'Mountain West', 2),
  ('12A', 'The Southwest', 3),
  ('12A', 'Texas & The Gulf', 4),
  ('12A', 'The Midwest', 5),
  ('12A', 'The South', 6),
  ('12A', 'New England', 7),
  ('12A', 'Mid-Atlantic', 8),
  ('12A', 'Alaska', 9),
  ('12A', 'Hawai‘i', 10),
  ('13A', 'British Columbia', 0),
  ('13A', 'The Rockies', 1),
  ('13A', 'The Prairies', 2),
  ('13A', 'Ontario', 3),
  ('13A', 'Québec', 4),
  ('13A', 'The Maritimes', 5),
  ('13A', 'The North', 6)
on conflict (region_code, name) do update set position = excluded.position;
