-- TravelWell.World — seed Destinations + Guides.
--
-- GENERATED by scripts/gen-catalog-seed.ts from the bundled catalog
-- (DESTINATIONS + GUIDES in places.ts). Do not hand-edit — regenerate after
-- catalog changes. Idempotent (ON CONFLICT DO UPDATE).
--
-- Apply:  supabase db push   (or paste into the Supabase SQL editor)
-- Requires 0001 (tables) and 0002 (regions, for the destinations.region_code FK).

-- Destinations ----------------------------------------------------------------
create table if not exists public.destinations (
  id          text primary key,
  region_code text not null references public.regions(code) on delete cascade,
  name        text not null,
  country     text not null,
  line        text not null,
  status      text not null check (status in ('live','future')),
  depth       text not null default 'verified' check (depth in ('verified','stub','cached')),
  img         text not null,
  sub_region  text,
  si          text[] not null default '{}',   -- Signature Interests this place serves
  feel        text[] not null default '{}',   -- feel/archetype tags (SI + feel = honest match)
  tier_range  text[] not null default '{}',   -- budget bands present (essential…ultra)
  price_band  text,                            -- coarse overall price label
  draw_rank   text check (draw_rank in ('anchor','core','emerging')),  -- surface order
  data        jsonb,                           -- full dossier (safety, booking, jewels, seo, timing…)
  position    int not null default 0
);

alter table public.destinations enable row level security;
do $$
begin
  create policy "read destinations" on public.destinations for select using (true);
exception when duplicate_object then null;
end $$;

-- Two-axis model (David-locked): status = shown | coming-soon; depth = how deep.
-- Evolve a pre-existing table (was status live|stub, no depth/sub_region)
-- idempotently BEFORE the upsert. Set depth from the old status, then flip the
-- shown-but-thin 'stub' rows to status 'live' (they stay shown; depth carries
-- the thinness), then swap the status constraint to live|future.
alter table public.destinations add column if not exists depth      text;
alter table public.destinations add column if not exists sub_region text;
update public.destinations set depth = case when status = 'stub' then 'stub' else 'verified' end where depth is null;
update public.destinations set status = 'live' where status = 'stub';
alter table public.destinations drop constraint if exists destinations_status_check;
alter table public.destinations add  constraint destinations_status_check check (status in ('live','future'));
alter table public.destinations drop constraint if exists destinations_depth_check;
alter table public.destinations add  constraint destinations_depth_check check (depth in ('verified','stub','cached'));
alter table public.destinations alter column depth set default 'verified';
-- Serving signals (the traveler-fit axes) + the dossier document. Self-heal an
-- existing table so a single re-run adds them.
alter table public.destinations add column if not exists si         text[] not null default '{}';
alter table public.destinations add column if not exists feel       text[] not null default '{}';
alter table public.destinations add column if not exists tier_range text[] not null default '{}';
alter table public.destinations add column if not exists price_band text;
alter table public.destinations add column if not exists draw_rank  text;
alter table public.destinations drop constraint if exists destinations_draw_rank_check;
alter table public.destinations add  constraint destinations_draw_rank_check check (draw_rank is null or draw_rank in ('anchor','core','emerging'));
alter table public.destinations add column if not exists data       jsonb;
create index if not exists destinations_si_idx        on public.destinations using gin (si);
create index if not exists destinations_draw_rank_idx on public.destinations (draw_rank);

insert into public.destinations (id, region_code, name, country, line, status, depth, img, sub_region, si, feel, tier_range, price_band, draw_rank, data, position) values
  ('paris', '01F', 'Paris', 'France', 'The first and last word in romance', 'live', 'verified', 'paris', null, '{}', '{}', '{}', null, null, null, 0),
  ('amalfi-x', '01F', 'Lake District', 'Germany', 'Storybook lakes and trails', 'live', 'stub', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 1),
  ('amsterdam', '01F', 'Amsterdam', 'Netherlands', 'Canals, galleries, easy charm', 'live', 'verified', 'venice', null, '{}', '{}', '{}', null, null, null, 2),
  ('alps', '01F', 'The Alps', 'Switzerland', 'Peaks, spas and slow trains', 'live', 'verified', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 3),
  ('santorini', '02F', 'Santorini', 'Greece', 'Whitewashed cliffs over a caldera', 'live', 'verified', 'santorini', null, '{}', '{}', '{}', null, null, null, 0),
  ('amalfi', '02F', 'Amalfi Coast', 'Italy', 'Lemon groves and vertical villages', 'live', 'verified', 'venice', null, '{}', '{}', '{}', null, null, null, 1),
  ('barcelona', '02F', 'Barcelona', 'Spain', 'Gaudí, tapas and Mediterranean light', 'live', 'verified', 'marrakech', null, '{}', '{}', '{}', null, null, null, 2),
  ('algarve', '02F', 'The Algarve', 'Portugal', 'Golden cliffs and quiet coves', 'live', 'stub', 'tropicalBeach', null, '{}', '{}', '{}', null, null, null, 3),
  ('reykjavik', '03F', 'Reykjavík & Ring Road', 'Iceland', 'Waterfalls, lava and aurora', 'live', 'verified', 'northernLights', null, '{}', '{}', '{}', null, null, null, 0),
  ('lofoten', '03F', 'Lofoten Islands', 'Norway', 'Sea-cliff drama above the Arctic Circle', 'live', 'stub', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 1),
  ('dubai', '04A', 'Dubai', 'UAE', 'Audacious, golden, around the clock', 'live', 'verified', 'dubai', null, '{}', '{}', '{}', null, null, null, 0),
  ('petra', '04A', 'Petra & Wadi Rum', 'Jordan', 'Rose-red city and red-sand desert', 'live', 'verified', 'desertDunes', null, '{}', '{}', '{}', null, null, null, 1),
  ('alula', '04A', 'AlUla', 'Saudi Arabia', 'Ancient tombs in a living desert', 'live', 'stub', 'desertDunes', null, '{}', '{}', '{}', null, null, null, 2),
  ('masai-mara', '05A', 'Maasai Mara', 'Kenya', 'Front-row seat to the Great Migration', 'live', 'verified', 'safariGiraffe', null, '{}', '{}', '{}', null, null, null, 0),
  ('serengeti', '05A', 'Serengeti', 'Tanzania', 'Endless plains, endless herds', 'live', 'verified', 'lion', null, '{}', '{}', '{}', null, null, null, 1),
  ('ngorongoro', '05A', 'Ngorongoro Crater', 'Tanzania', 'A natural amphitheatre of wildlife', 'live', 'verified', 'elephant', null, '{}', '{}', '{}', null, null, null, 2),
  ('volcanoes', '05A', 'Volcanoes NP', 'Rwanda', 'Mountain gorillas in the mist', 'live', 'stub', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 3),
  ('cape-town-south-africa', '06A', 'Cape Town', 'South Africa', 'Where the mountain meets two oceans', 'live', 'verified', 'oceanAerial', 'South Africa', '{}', '{}', '{}', null, null, null, 0),
  ('kruger', '06A', 'Greater Kruger', 'South Africa', 'Big Five in the lowveld', 'live', 'verified', 'elephant', 'South Africa', '{}', '{}', '{}', null, null, null, 1),
  ('sossusvlei', '06A', 'Sossusvlei', 'Namibia', 'The world''s tallest dunes', 'live', 'stub', 'desertDunes', 'Namibia Desert & Coast', '{}', '{}', '{}', null, null, null, 2),
  ('bali', '07A', 'Bali', 'Indonesia', 'Rice terraces, temples and surf', 'live', 'verified', 'baliRice', null, '{}', '{}', '{}', null, null, null, 0),
  ('bangkok', '07A', 'Bangkok', 'Thailand', 'Street food capital of the world', 'live', 'verified', 'restaurant', null, '{}', '{}', '{}', null, null, null, 1),
  ('kyoto-x', '07A', 'Phuket & Phi Phi', 'Thailand', 'Limestone islands and warm seas', 'live', 'verified', 'tropicalBeach', null, '{}', '{}', '{}', null, null, null, 2),
  ('siem-reap', '07A', 'Siem Reap', 'Cambodia', 'Sunrise over Angkor Wat', 'live', 'stub', 'kyoto', null, '{}', '{}', '{}', null, null, null, 3),
  ('kyoto', '08A', 'Kyoto', 'Japan', 'Geisha districts and golden temples', 'live', 'verified', 'kyoto', null, '{}', '{}', '{}', null, null, null, 0),
  ('tokyo', '08A', 'Tokyo', 'Japan', 'Neon, Michelin stars and calm shrines', 'live', 'verified', 'dubai', null, '{}', '{}', '{}', null, null, null, 1),
  ('seoul', '08A', 'Seoul', 'South Korea', 'Palaces, markets and midnight food', 'live', 'stub', 'marrakech', null, '{}', '{}', '{}', null, null, null, 2),
  ('queenstown', '09P', 'Queenstown', 'New Zealand', 'Adventure capital of the south', 'live', 'verified', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 0),
  ('bora-bora', '09P', 'Bora Bora', 'French Polynesia', 'Overwater bungalows on a lagoon', 'live', 'verified', 'maldivesResort', null, '{}', '{}', '{}', null, null, null, 1),
  ('gbr', '09P', 'Great Barrier Reef', 'Australia', 'The largest living thing on Earth', 'live', 'stub', 'oceanAerial', null, '{}', '{}', '{}', null, null, null, 2),
  ('machu', '10S', 'Machu Picchu', 'Peru', 'The lost city in the clouds', 'live', 'verified', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 0),
  ('patagonia', '10S', 'Patagonia', 'Chile / Argentina', 'Granite spires and turquoise lakes', 'live', 'verified', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 1),
  ('cartagena', '10S', 'Cartagena', 'Colombia', 'Walled city of color and rhythm', 'live', 'stub', 'marrakech', null, '{}', '{}', '{}', null, null, null, 2),
  ('turks', '11C', 'Turks & Caicos', 'Turks & Caicos', 'Grace Bay''s impossible blues', 'live', 'verified', 'oceanAerial', 'Turks & Caicos', '{}', '{}', '{}', null, null, null, 0),
  ('st-lucia', '11C', 'St. Lucia', 'St. Lucia', 'The Pitons above the sea', 'live', 'verified', 'tropicalBeach', 'Eastern Caribbean — Windwards & South', '{}', '{}', '{}', null, null, null, 1),
  ('exuma', '11C', 'The Exumas', 'Bahamas', 'Sandbars and swimming pigs', 'live', 'stub', 'maldivesResort', 'Bahamas', '{}', '{}', '{}', null, null, null, 2),
  ('banff', '13A', 'Banff & Lake Louise', 'Canada', 'Turquoise lakes under the Rockies', 'live', 'verified', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 0),
  ('vancouver', '13A', 'Vancouver', 'Canada', 'Sea, city and mountains at once', 'live', 'stub', 'oceanAerial', null, '{}', '{}', '{}', null, null, null, 1)
on conflict (id) do update set
  region_code = excluded.region_code, name = excluded.name, country = excluded.country,
  line = excluded.line, status = excluded.status, depth = excluded.depth, img = excluded.img,
  sub_region = excluded.sub_region, si = excluded.si, feel = excluded.feel, tier_range = excluded.tier_range,
  price_band = excluded.price_band, draw_rank = excluded.draw_rank, data = excluded.data, position = excluded.position;

-- Seed is authoritative: drop any destination no longer in the catalog — e.g.
-- a row left behind by a key rename (cape-town -> cape-town-south-africa). Safe
-- while every destination comes from this seed; once cache-back writes
-- atlas-sourced rows, scope this by a source column instead.
delete from public.destinations where id not in ('paris', 'amalfi-x', 'amsterdam', 'alps', 'santorini', 'amalfi', 'barcelona', 'algarve', 'reykjavik', 'lofoten', 'dubai', 'petra', 'alula', 'masai-mara', 'serengeti', 'ngorongoro', 'volcanoes', 'cape-town-south-africa', 'kruger', 'sossusvlei', 'bali', 'bangkok', 'kyoto-x', 'siem-reap', 'kyoto', 'tokyo', 'seoul', 'queenstown', 'bora-bora', 'gbr', 'machu', 'patagonia', 'cartagena', 'turks', 'st-lucia', 'exuma', 'banff', 'vancouver');

-- Guides ----------------------------------------------------------------------
create table if not exists public.guides (
  id        text primary key,
  type      text not null,
  title     text not null,
  lede      text not null,
  read      text not null,
  updated   text not null,
  img       text not null,
  si        text not null,
  region    text not null,
  position  int not null default 0
);

alter table public.guides enable row level security;
do $$
begin
  create policy "read guides" on public.guides for select using (true);
exception when duplicate_object then null;
end $$;

insert into public.guides (id, type, title, lede, read, updated, img, si, region, position) values
  ('migration-timing', 'Seasonal', 'When to See the Great Migration', 'Month by month, where the herds are and where to be standing when they cross.', '6 min', 'Jun 2026', 'safariGiraffe', 'safari', '05A', 0),
  ('safari-packing', 'How-To', 'What to Pack for a Safari', 'The honest list — layers, optics, and the three things first-timers always forget.', '4 min', 'May 2026', 'desertDunes', 'safari', '05A', 1),
  ('morocco-top8', 'Top List', 'Morocco in 8 Unforgettable Stops', 'A ranked route through imperial cities, desert camps and the Atlas mountains.', '9 min', 'Apr 2026', 'marrakech', 'heritage', '04A', 2),
  ('first-safari', 'Field Guide', 'Your First Safari, Demystified', 'Camps vs lodges, private vs shared, malaria, tipping — everything no one tells you.', '8 min', 'Jun 2026', 'lion', 'safari', '05A', 3),
  ('honeymoon-where', 'Field Guide', 'Where to Honeymoon, by Vibe', 'Barefoot beach, alpine hush, or city romance — matched to who you are as a couple.', '7 min', 'May 2026', 'santorini', 'romance', '11C', 4),
  ('japan-cherry', 'Seasonal', 'Chasing Cherry Blossom in Japan', 'The forecast, the crowds, and the quiet temples where sakura still feels secret.', '6 min', 'Mar 2026', 'kyoto', 'culture', '08A', 5),
  ('med-sailing', 'How-To', 'Sailing the Mediterranean, Stress-Free', 'Crewed vs bareboat, the best weeks to go, and how to island-hop without rushing.', '5 min', 'Apr 2026', 'santorini', 'sailing', '02F', 6),
  ('patagonia-trek', 'Field Guide', 'Trekking Patagonia: The W vs The O', 'Two legendary routes compared — distance, difficulty, huts, and the views that earn it.', '10 min', 'Mar 2026', 'mountainValley', 'adventure', '10S', 7),
  ('culinary-cities', 'Top List', '10 Cities Worth Flying For (to Eat)', 'Where the table is the destination — from street stalls to three stars.', '8 min', 'May 2026', 'restaurant', 'culinary', '01F', 8)
on conflict (id) do update set
  type = excluded.type, title = excluded.title, lede = excluded.lede, read = excluded.read,
  updated = excluded.updated, img = excluded.img, si = excluded.si, region = excluded.region,
  position = excluded.position;
