-- TravelWell.World — seed Destinations + Guides.
--
-- GENERATED by scripts/gen-catalog-seed.ts from the bundled catalog
-- (DESTINATIONS + GUIDES in places.ts). Do not hand-edit — regenerate after
-- catalog changes. Idempotent (ON CONFLICT DO UPDATE).
--
-- Apply:  supabase db push   (or paste into the Supabase SQL editor)
-- Requires 0001 (tables) and 0002 (regions, for the destinations.region_code FK).

-- Destinations ----------------------------------------------------------------
create table if not exists public.destinations (
  id          text primary key,
  region_code text not null references public.regions(code) on delete cascade,
  name        text not null,
  country     text not null,
  line        text not null,
  status      text not null check (status in ('live','future')),
  depth       text not null default 'verified' check (depth in ('verified','stub','cached')),
  img         text not null,
  sub_region  text,
  si          text[] not null default '{}',   -- Signature Interests this place serves
  feel        text[] not null default '{}',   -- feel/archetype tags (SI + feel used together, never one alone)
  tier_range  text[] not null default '{}',   -- budget bands present (essential…ultra)
  price_band  text,                            -- coarse overall price label
  draw_rank   text check (draw_rank in ('anchor','core','emerging')),  -- surface order
  data        jsonb,                           -- full dossier (safety, booking, jewels, seo, timing…)
  position    int not null default 0
);

alter table public.destinations enable row level security;
do $$
begin
  create policy "read destinations" on public.destinations for select using (true);
exception when duplicate_object then null;
end $$;

-- Two-axis model (David-locked): status = shown | coming-soon; depth = how deep.
-- Evolve a pre-existing table (was status live|stub, no depth/sub_region)
-- idempotently BEFORE the upsert. Set depth from the old status, then flip the
-- shown-but-thin 'stub' rows to status 'live' (they stay shown; depth carries
-- the thinness), then swap the status constraint to live|future.
alter table public.destinations add column if not exists depth      text;
alter table public.destinations add column if not exists sub_region text;
update public.destinations set depth = case when status = 'stub' then 'stub' else 'verified' end where depth is null;
update public.destinations set status = 'live' where status = 'stub';
alter table public.destinations drop constraint if exists destinations_status_check;
alter table public.destinations add  constraint destinations_status_check check (status in ('live','future'));
alter table public.destinations drop constraint if exists destinations_depth_check;
alter table public.destinations add  constraint destinations_depth_check check (depth in ('verified','stub','cached'));
alter table public.destinations alter column depth set default 'verified';
-- Serving signals (the traveler-fit axes) + the dossier document. Self-heal an
-- existing table so a single re-run adds them.
alter table public.destinations add column if not exists si         text[] not null default '{}';
alter table public.destinations add column if not exists feel       text[] not null default '{}';
alter table public.destinations add column if not exists tier_range text[] not null default '{}';
alter table public.destinations add column if not exists price_band text;
alter table public.destinations add column if not exists draw_rank  text;
alter table public.destinations drop constraint if exists destinations_draw_rank_check;
alter table public.destinations add  constraint destinations_draw_rank_check check (draw_rank is null or draw_rank in ('anchor','core','emerging'));
alter table public.destinations add column if not exists data       jsonb;
create index if not exists destinations_si_idx        on public.destinations using gin (si);
create index if not exists destinations_draw_rank_idx on public.destinations (draw_rank);

-- destinations 1-44 of 44 (chunk 1/1)
insert into public.destinations (id, region_code, name, country, line, status, depth, img, sub_region, si, feel, tier_range, price_band, draw_rank, data, position) values
  ('paris-france', '01F', 'Paris', 'France', 'The first and last word in romance', 'live', 'verified', 'paris', null, '{}', '{}', '{}', null, null, null, 0),
  ('amsterdam-netherlands', '01F', 'Amsterdam', 'Netherlands', 'Canals, galleries, easy charm', 'live', 'verified', 'venice', null, '{}', '{}', '{}', null, null, null, 1),
  ('swiss-alps-switzerland', '01F', 'The Alps', 'Switzerland', 'Peaks, spas and slow trains', 'live', 'verified', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 2),
  ('zermatt-switzerland', '01F', 'Zermatt', 'Switzerland', 'Car-free skiing under the Matterhorn', 'live', 'verified', 'mountainValley', 'Valais Alps', '{"ski","wellness"}', '{"alpine","dramatic","refined"}', '{"premier","luxury","ultra"}', 'luxury', 'anchor', '{"safety":{"advisory_level":"L1","posture":"book-freely","booking_hold":false,"notes":"Normal precautions; alpine risk is weather + avalanche, managed by resort patrol — ski in-bounds and heed closures.","source":"US State Dept L1 / Swiss authorities","verified":"2026-06"},"timing":{"season":"Dec–Apr","best_months":[1,2,3],"notes":"Glacier skiing extends the season; Feb–Mar for the most reliable snow."},"jewels":[{"name":"Gornergrat cog railway at sunrise","tier":"premier","when":"clear mornings","blurb":"The Matterhorn head-on, before the crowds.","si":"ski","commission":"Rail + experience partner — commission lane"},{"name":"Glacier spa evening after the slopes","tier":"luxury","when":"any evening","blurb":"Thermal pools with the peak in the window — the Wellness side of a ski week.","si":"wellness","commission":"Hotel-spa affiliate"}],"faq":[{"q":"Do I need a car in Zermatt?","a":"No — Zermatt is car-free. Park in Täsch and take the 12-minute shuttle train; everything in the village is walkable or by electric taxi.","source":"Zermatt Tourism"},{"q":"When is the snow most reliable?","a":"February and March are the most dependable, but the glacier keeps skiing open into spring — and even summer on the Theodul.","source":"Verified 2026-06"}]}'::jsonb, 3),
  ('st-anton-austria', '01F', 'St. Anton am Arlberg', 'Austria', 'The birthplace of alpine skiing — steep, deep, legendary', 'live', 'verified', 'mountainValley', 'Arlberg / Tyrol', '{"ski","adventure"}', '{"alpine","rugged","festive"}', '{"comfort","premier","luxury"}', 'premier', 'core', '{"safety":{"advisory_level":"L1","posture":"book-freely","booking_hold":false,"notes":"Normal precautions; renowned off-piste carries real avalanche risk — hire a certified guide off the marked runs.","source":"US State Dept L1 / Austrian authorities","verified":"2026-06"},"timing":{"season":"Dec–Apr","best_months":[1,2,3],"notes":"Legendary après-ski; Jan–Mar for the deepest snow on the Arlberg."},"jewels":[{"name":"Off-piste day with an Arlberg guide","tier":"premier","when":"after fresh snow","blurb":"The terrain that made the sport, read by someone who knows it.","si":"ski","commission":"Certified guide bureau — commission lane"},{"name":"Last run into the Mooserwirt","tier":"comfort","when":"3pm onward","blurb":"Ski straight into the Arlberg''s most infamous après bar — the party starts before the lifts close.","si":"ski","commission":"Partner venue"}],"faq":[{"q":"Is St. Anton good for beginners?","a":"It''s famous for expert terrain, but the Nasserein and Gampen slopes are gentle, well-groomed blues — and the Arlberg ski schools are among the oldest in the world.","source":"Verified 2026-06"},{"q":"How do I get to St. Anton?","a":"Fly to Innsbruck (~1hr) or Zurich (~2hr) and take the train straight in — the station is in the village, no transfer needed.","source":"Arlberg tourism"}]}'::jsonb, 4),
  ('chamonix-france', '01F', 'Chamonix', 'France', 'Mont Blanc above, glaciers below — the mountaineer''s capital', 'live', 'verified', 'mountainValley', 'Haute-Savoie / French Alps', '{"ski","adventure"}', '{"alpine","dramatic","rugged"}', '{"comfort","premier","luxury"}', 'premier', 'core', '{"safety":{"advisory_level":"L2","posture":"book-freely","booking_hold":false,"notes":"Exercise increased caution (France-wide, mainly urban). In the valley the practical risk is the mountain rather than crime — high-alpine routes and the Vallée Blanche need a qualified guide.","source":"US State Dept L2 / French authorities","verified":"2026-06"},"timing":{"season":"Dec–Apr","best_months":[1,2,3],"notes":"Serious terrain; the Vallée Blanche is spring-dependent — check conditions."},"jewels":[{"name":"Aiguille du Midi cable car","tier":"comfort","when":"clear days","blurb":"3,842m and the roof of Europe in twenty minutes.","si":"adventure","commission":"Lift + experience partner"},{"name":"The Vallée Blanche with a guide","tier":"premier","when":"spring conditions","blurb":"20km off-piste from 3,842m to the valley — glacier, séracs, a mountain guide reading every step.","si":"adventure","commission":"Guide bureau — commission lane","source":"Compagnie du Mont-Blanc (Aiguille du Midi altitude and descent)"}],"faq":[{"q":"Do I need to be an expert to ski Chamonix?","a":"The linked areas (Brévent, Flégère, Grands Montets) have plenty for intermediates; the legendary off-piste and the Vallée Blanche need a qualified guide.","source":"Verified 2026-06"},{"q":"Can you ski the Vallée Blanche without a guide?","a":"No — it crosses a live glacier with crevasses and séracs. Always go with a certified mountain guide, and it''s spring-condition dependent.","source":"Compagnie des Guides"}]}'::jsonb, 5),
  ('st-moritz-switzerland', '01F', 'St. Moritz', 'Switzerland', 'Where alpine glamour was invented — and still lives', 'live', 'verified', 'mountainValley', 'Engadin / Graubünden', '{"ski","wellness"}', '{"alpine","refined","polished"}', '{"luxury","ultra"}', 'ultra', 'anchor', '{"safety":{"advisory_level":"L1","posture":"book-freely","booking_hold":false,"notes":"Normal precautions; alpine risk is weather + avalanche, managed by resort patrol — ski in-bounds and heed closures.","source":"US State Dept L1 / Swiss authorities","verified":"2026-06"},"timing":{"season":"Dec–Apr","best_months":[1,2,3],"notes":"High, sunny Engadin snow; Jan–Feb for the classic season and the frozen-lake events."},"jewels":[{"name":"A night at Badrutt''s, the lake frozen below","tier":"ultra","when":"peak season","blurb":"The birthplace of winter tourism, taken at full glamour.","si":"wellness","commission":"Hotel partner — commission lane"},{"name":"White Turf racing on the frozen lake","tier":"luxury","when":"February Sundays","blurb":"Thoroughbreds thunder across the frozen St. Moritzersee — a century-old spectacle.","si":"spectator","commission":"Event + hospitality partner"}],"faq":[{"q":"When is the frozen-lake season?","a":"The lake freezes solid enough for events from late January through February — White Turf racing, snow polo, and the gourmet festival all run then.","source":"St. Moritz Tourism"},{"q":"Is St. Moritz only for luxury travellers?","a":"The glamour is real, but the Engadin''s high, sunny slopes and the shared lift network serve every level — not every bed is a palace.","source":"Verified 2026-06"}]}'::jsonb, 6),
  ('courchevel-france', '01F', 'Courchevel', 'France', 'The luxury address of the world''s largest ski area', 'live', 'verified', 'mountainValley', 'Trois Vallées / Savoie', '{"ski","wellness"}', '{"alpine","refined","polished"}', '{"premier","luxury","ultra"}', 'luxury', 'anchor', '{"safety":{"advisory_level":"L2","posture":"book-freely","booking_hold":false,"notes":"Exercise increased caution (France-wide, mainly urban). In resort the practical risk is the mountain rather than crime — off-piste across the Trois Vallées needs a qualified guide.","source":"US State Dept L2 / French authorities","verified":"2026-06"},"timing":{"season":"Dec–Apr","best_months":[1,2,3],"notes":"Gateway to the 3 Vallées — 600km of linked pistes; Feb–Mar for depth and sun."},"jewels":[{"name":"First tracks across the Trois Vallées","tier":"premier","when":"after a snowfall","blurb":"The world''s largest linked ski area, empty, at dawn.","si":"ski","commission":"Lift + guide partner"},{"name":"A Michelin dinner at 1850","tier":"luxury","when":"any evening","blurb":"Courchevel 1850 has more Michelin stars than any ski resort on earth — the Eat-Well side of a ski week.","si":"culinary","commission":"Restaurant partner"}],"faq":[{"q":"What do the Courchevel ''levels'' (1850, 1650…) mean?","a":"They''re villages at different altitudes on the same mountain — 1850 is the glossy top address; 1650 (Moriond) and 1550 are quieter and better value, all on the lift network.","source":"Verified 2026-06"},{"q":"Is it really the world''s largest ski area?","a":"Courchevel is the gateway to Les 3 Vallées — around 600km of linked, lift-served pistes, the largest connected ski area in the world.","source":"Les 3 Vallées"}]}'::jsonb, 7),
  ('cortina-dampezzo-italy', '01F', 'Cortina d''Ampezzo', 'Italy', 'The Queen of the Dolomites — a 2026 Olympic host', 'live', 'verified', 'mountainValley', 'Dolomites / Veneto', '{"ski","adventure"}', '{"alpine","dramatic","refined"}', '{"premier","luxury"}', 'luxury', 'anchor', '{"safety":{"advisory_level":"L2","posture":"book-freely","booking_hold":false,"notes":"Exercise increased caution (Italy-wide, mainly urban posture). In Cortina the practical risk is the mountain rather than crime — Dolomiti Superski off-piste and via ferrata need a guide.","source":"US State Dept L2 / Italian authorities","verified":"2026-06"},"timing":{"season":"Dec–Apr","best_months":[1,2,3],"notes":"Co-hosts the Milano-Cortina 2026 Winter Olympics — book well ahead for the Games window."},"jewels":[{"name":"Sunset on the Tofane from a Dolomiti rifugio","tier":"premier","when":"clear afternoons","blurb":"Pink light on the Dolomites, a plate of casunziei, the pistes gone quiet.","si":"ski","commission":"Mountain-hut partner"},{"name":"The Sellaronda circuit in a day","tier":"premier","when":"clear midweek days","blurb":"Ski a full loop around the Sella massif on one lift pass — 40km of pistes, four valleys, lunch in a different dialect.","si":"ski","commission":"Dolomiti Superski lane","source":"Dolomiti Superski (Sellaronda circuit)"}],"faq":[{"q":"Is Cortina part of a bigger ski area?","a":"Yes — it''s on the Dolomiti Superski pass: 12 areas and ~1,200km of pistes on one ticket, with the famous Sellaronda circuit nearby.","source":"Dolomiti Superski"},{"q":"When are the 2026 Winter Games in Cortina?","a":"Milano-Cortina host in February 2026; Cortina holds the women''s alpine and the sliding events — book far ahead for that window.","source":"Verified 2026-06"}]}'::jsonb, 8),
  ('kitzbuhel-austria', '01F', 'Kitzbühel', 'Austria', 'A medieval ski town behind the world''s toughest downhill', 'live', 'verified', 'mountainValley', 'Kitzbühel Alps / Tyrol', '{"ski","adventure"}', '{"alpine","historic","festive"}', '{"comfort","premier","luxury"}', 'premier', 'core', '{"safety":{"advisory_level":"L1","posture":"book-freely","booking_hold":false,"notes":"Normal precautions; the Hahnenkamm''s Streif is expert-only — the resort''s blue and red runs suit everyone, off-piste wants a guide.","source":"US State Dept L1 / Austrian authorities","verified":"2026-06"},"timing":{"season":"Dec–Apr","best_months":[1,2,3],"notes":"The Hahnenkamm race is late January — electric, but book far ahead; Feb–Mar is quieter and deep."},"jewels":[{"name":"Standing at the top of the Streif","tier":"comfort","when":"a clear morning","blurb":"Look down the most feared downhill in ski racing — then take the gentle way home.","si":"ski","commission":"Lift partner"},{"name":"Hahnenkamm race weekend","tier":"premier","when":"late January","blurb":"The world''s most feared downhill, from the grandstand — then the town''s biggest party.","si":"spectator","commission":"Event + hospitality partner"}],"faq":[{"q":"Can normal skiers ski the Streif?","a":"The race line is expert-only and often closed, but you can ski its famous sections in gentler condition, and the rest of the Kitzbühel Alps suits every level.","source":"Verified 2026-06"},{"q":"When is the Hahnenkamm race?","a":"Mid-to-late January — electric, but the town is packed; February and March are quieter with reliable snow.","source":"Kitzbühel Tourism"}]}'::jsonb, 9),
  ('santorini-greece', '02F', 'Santorini', 'Greece', 'Whitewashed cliffs over a caldera', 'live', 'verified', 'santorini', null, '{}', '{}', '{}', null, null, null, 0),
  ('amalfi-coast-italy', '02F', 'Amalfi Coast', 'Italy', 'Lemon groves and vertical villages', 'live', 'verified', 'venice', null, '{}', '{}', '{}', null, null, null, 1),
  ('barcelona-spain', '02F', 'Barcelona', 'Spain', 'Gaudí, tapas and Mediterranean light', 'live', 'verified', 'marrakech', null, '{}', '{}', '{}', null, null, null, 2),
  ('algarve-portugal', '02F', 'The Algarve', 'Portugal', 'Golden cliffs and quiet coves', 'live', 'stub', 'tropicalBeach', null, '{}', '{}', '{}', null, null, null, 3),
  ('reykjavik-iceland', '03F', 'Reykjavík & Ring Road', 'Iceland', 'Waterfalls, lava and aurora', 'live', 'verified', 'northernLights', null, '{}', '{}', '{}', null, null, null, 0),
  ('lofoten-islands-norway', '03F', 'Lofoten Islands', 'Norway', 'Sea-cliff drama above the Arctic Circle', 'live', 'stub', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 1),
  ('dubai-united-arab-emirates', '04A', 'Dubai', 'UAE', 'Audacious, golden, around the clock', 'live', 'verified', 'dubai', null, '{}', '{}', '{}', null, null, null, 0),
  ('petra-jordan', '04A', 'Petra & Wadi Rum', 'Jordan', 'Rose-red city and red-sand desert', 'live', 'verified', 'desertDunes', null, '{}', '{}', '{}', null, null, null, 1),
  ('alula-saudi-arabia', '04A', 'AlUla', 'Saudi Arabia', 'Ancient tombs in a living desert', 'live', 'stub', 'desertDunes', null, '{}', '{}', '{}', null, null, null, 2),
  ('maasai-mara-kenya', '05A', 'Maasai Mara', 'Kenya', 'Front-row seat to the Great Migration', 'live', 'verified', 'safariGiraffe', null, '{}', '{}', '{}', null, null, null, 0),
  ('serengeti-tanzania', '05A', 'Serengeti', 'Tanzania', 'Endless plains, endless herds', 'live', 'verified', 'lion', null, '{}', '{}', '{}', null, null, null, 1),
  ('ngorongoro-tanzania', '05A', 'Ngorongoro Crater', 'Tanzania', 'A natural amphitheatre of wildlife', 'live', 'verified', 'elephant', null, '{}', '{}', '{}', null, null, null, 2),
  ('volcanoes-national-park-rwanda', '05A', 'Volcanoes NP', 'Rwanda', 'Mountain gorillas in the mist', 'live', 'stub', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 3),
  ('cape-town-south-africa', '06A', 'Cape Town', 'South Africa', 'Where the mountain meets two oceans', 'live', 'verified', 'oceanAerial', 'South Africa', '{}', '{}', '{}', null, null, null, 0),
  ('greater-kruger-south-africa', '06A', 'Greater Kruger', 'South Africa', 'Big Five in the lowveld', 'live', 'verified', 'elephant', 'South Africa', '{}', '{}', '{}', null, null, null, 1),
  ('sossusvlei-namibia', '06A', 'Sossusvlei', 'Namibia', 'The world''s tallest dunes', 'live', 'stub', 'desertDunes', 'Namibia Desert & Coast', '{}', '{}', '{}', null, null, null, 2),
  ('bali-indonesia', '07A', 'Bali', 'Indonesia', 'Rice terraces, temples and surf', 'live', 'verified', 'baliRice', null, '{}', '{}', '{}', null, null, null, 0),
  ('bangkok-thailand', '07A', 'Bangkok', 'Thailand', 'Street food capital of the world', 'live', 'verified', 'restaurant', null, '{}', '{}', '{}', null, null, null, 1),
  ('phuket-thailand', '07A', 'Phuket & Phi Phi', 'Thailand', 'Limestone islands and warm seas', 'live', 'verified', 'tropicalBeach', null, '{}', '{}', '{}', null, null, null, 2),
  ('siem-reap-cambodia', '07A', 'Siem Reap', 'Cambodia', 'Sunrise over Angkor Wat', 'live', 'stub', 'kyoto', null, '{}', '{}', '{}', null, null, null, 3),
  ('kyoto-japan', '08A', 'Kyoto', 'Japan', 'Geisha districts and golden temples', 'live', 'verified', 'kyoto', null, '{}', '{}', '{}', null, null, null, 0),
  ('tokyo-japan', '08A', 'Tokyo', 'Japan', 'Neon, Michelin stars and calm shrines', 'live', 'verified', 'dubai', null, '{}', '{}', '{}', null, null, null, 1),
  ('seoul-south-korea', '08A', 'Seoul', 'South Korea', 'Palaces, markets and midnight food', 'live', 'stub', 'marrakech', null, '{}', '{}', '{}', null, null, null, 2),
  ('queenstown-new-zealand', '09P', 'Queenstown', 'New Zealand', 'Adventure capital of the south', 'live', 'verified', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 0),
  ('bora-bora-french-polynesia', '09P', 'Bora Bora', 'French Polynesia', 'Overwater bungalows on a lagoon', 'live', 'verified', 'maldivesResort', null, '{}', '{}', '{}', null, null, null, 1),
  ('great-barrier-reef-australia', '09P', 'Great Barrier Reef', 'Australia', 'The largest living thing on Earth', 'live', 'stub', 'oceanAerial', null, '{}', '{}', '{}', null, null, null, 2),
  ('machu-picchu-peru', '10S', 'Machu Picchu', 'Peru', 'The lost city in the clouds', 'live', 'verified', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 0),
  ('patagonia-chile-argentina', '10S', 'Patagonia', 'Chile / Argentina', 'Granite spires and turquoise lakes', 'live', 'verified', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 1),
  ('cartagena-colombia', '10S', 'Cartagena', 'Colombia', 'Walled city of color and rhythm', 'live', 'stub', 'marrakech', null, '{}', '{}', '{}', null, null, null, 2),
  ('turks-and-caicos', '11C', 'Turks & Caicos', 'Turks & Caicos', 'Grace Bay''s impossible blues', 'live', 'verified', 'oceanAerial', 'Turks & Caicos', '{}', '{}', '{}', null, null, null, 0),
  ('st-lucia', '11C', 'St. Lucia', 'St. Lucia', 'The Pitons above the sea', 'live', 'verified', 'tropicalBeach', 'Eastern Caribbean — Windwards & South', '{}', '{}', '{}', null, null, null, 1),
  ('exuma-bahamas', '11C', 'The Exumas', 'Bahamas', 'Sandbars and swimming pigs', 'live', 'stub', 'maldivesResort', 'Bahamas', '{}', '{}', '{}', null, null, null, 2),
  ('banff-canada', '13A', 'Banff & Lake Louise', 'Canada', 'Turquoise lakes under the Rockies', 'live', 'verified', 'mountainValley', null, '{}', '{}', '{}', null, null, null, 0),
  ('vancouver-canada', '13A', 'Vancouver', 'Canada', 'Sea, city and mountains at once', 'live', 'stub', 'oceanAerial', null, '{}', '{}', '{}', null, null, null, 1)
on conflict (id) do update set
  region_code = excluded.region_code, name = excluded.name, country = excluded.country,
  line = excluded.line, status = excluded.status, depth = excluded.depth, img = excluded.img,
  sub_region = excluded.sub_region, si = excluded.si, feel = excluded.feel, tier_range = excluded.tier_range,
  price_band = excluded.price_band, draw_rank = excluded.draw_rank, data = excluded.data, position = excluded.position;

-- Seed is authoritative: drop any destination no longer in the catalog — e.g.
-- a row left behind by a key rename (cape-town -> cape-town-south-africa). Safe
-- while every destination comes from this seed; once cache-back writes
-- atlas-sourced rows, scope this by a source column instead.
delete from public.destinations where id not in ('paris-france', 'amsterdam-netherlands', 'swiss-alps-switzerland', 'zermatt-switzerland', 'st-anton-austria', 'chamonix-france', 'st-moritz-switzerland', 'courchevel-france', 'cortina-dampezzo-italy', 'kitzbuhel-austria', 'santorini-greece', 'amalfi-coast-italy', 'barcelona-spain', 'algarve-portugal', 'reykjavik-iceland', 'lofoten-islands-norway', 'dubai-united-arab-emirates', 'petra-jordan', 'alula-saudi-arabia', 'maasai-mara-kenya', 'serengeti-tanzania', 'ngorongoro-tanzania', 'volcanoes-national-park-rwanda', 'cape-town-south-africa', 'greater-kruger-south-africa', 'sossusvlei-namibia', 'bali-indonesia', 'bangkok-thailand', 'phuket-thailand', 'siem-reap-cambodia', 'kyoto-japan', 'tokyo-japan', 'seoul-south-korea', 'queenstown-new-zealand', 'bora-bora-french-polynesia', 'great-barrier-reef-australia', 'machu-picchu-peru', 'patagonia-chile-argentina', 'cartagena-colombia', 'turks-and-caicos', 'st-lucia', 'exuma-bahamas', 'banff-canada', 'vancouver-canada');

-- Guides ----------------------------------------------------------------------
create table if not exists public.guides (
  id        text primary key,
  type      text not null,
  title     text not null,
  lede      text not null,
  read      text not null,
  updated   text not null,
  img       text not null,
  si        text not null,
  region    text not null,
  position  int not null default 0
);

alter table public.guides enable row level security;
do $$
begin
  create policy "read guides" on public.guides for select using (true);
exception when duplicate_object then null;
end $$;

insert into public.guides (id, type, title, lede, read, updated, img, si, region, position) values
  ('migration-timing', 'Seasonal', 'When to See the Great Migration', 'Month by month, where the herds are and where to be standing when they cross.', '6 min', 'Jun 2026', 'safariGiraffe', 'safari', '05A', 0),
  ('safari-packing', 'How-To', 'What to Pack for a Safari', 'The straight list — layers, optics, and the three things first-timers always forget.', '4 min', 'May 2026', 'desertDunes', 'safari', '05A', 1),
  ('morocco-top8', 'Top List', 'Morocco in 8 Unforgettable Stops', 'A ranked route through imperial cities, desert camps and the Atlas mountains.', '9 min', 'Apr 2026', 'marrakech', 'heritage', '04A', 2),
  ('first-safari', 'Field Guide', 'Your First Safari, Demystified', 'Camps vs lodges, private vs shared, malaria, tipping — everything no one tells you.', '8 min', 'Jun 2026', 'lion', 'safari', '05A', 3),
  ('honeymoon-where', 'Field Guide', 'Where to Honeymoon, by Vibe', 'Barefoot beach, alpine hush, or city romance — matched to who you are as a couple.', '7 min', 'May 2026', 'santorini', 'romance', '11C', 4),
  ('japan-cherry', 'Seasonal', 'Chasing Cherry Blossom in Japan', 'The forecast, the crowds, and the quiet temples where sakura still feels secret.', '6 min', 'Mar 2026', 'kyoto', 'culture', '08A', 5),
  ('med-sailing', 'How-To', 'Sailing the Mediterranean, Stress-Free', 'Crewed vs bareboat, the best weeks to go, and how to island-hop without rushing.', '5 min', 'Apr 2026', 'santorini', 'sailing', '02F', 6),
  ('patagonia-trek', 'Field Guide', 'Trekking Patagonia: The W vs The O', 'Two legendary routes compared — distance, difficulty, huts, and the views that earn it.', '10 min', 'Mar 2026', 'mountainValley', 'adventure', '10S', 7),
  ('culinary-cities', 'Top List', '10 Cities Worth Flying For (to Eat)', 'Where the table is the destination — from street stalls to three stars.', '8 min', 'May 2026', 'restaurant', 'culinary', '01F', 8)
on conflict (id) do update set
  type = excluded.type, title = excluded.title, lede = excluded.lede, read = excluded.read,
  updated = excluded.updated, img = excluded.img, si = excluded.si, region = excluded.region,
  position = excluded.position;
