-- TravelWell.World — Local & temporal signals (Atlas's "knows what's happening").
--
-- GENERATED by scripts/gen-catalog-seed.ts from src/data/local-signals.ts.
-- Do not hand-edit — regenerate after authoring. Idempotent (ON CONFLICT).
-- World-readable: Atlas + Whispers read it; curated now, feeds/provider later.
--
-- Apply:  supabase db push   (or paste into the Supabase SQL editor)
-- Requires 0001 + 0002 (regions) and 0005 (destinations, for the FKs).

-- destination_id is a free-text place key (signals name places we don't model
-- in the destinations catalog yet), so it is intentionally NOT a foreign key.
create table if not exists public.local_signals (
  id            text primary key,
  destination_id text,
  region_code   text references public.regions(code),
  si            text[] not null default '{}',
  wells         text[] not null default '{}',
  kind          text not null check (kind in ('event','schedule','opening','lookahead')),
  horizon       text not null default 'now' check (horizon in ('now','soon','lookahead')),
  title         text not null,
  blurb         text,
  href          text,
  starts_on     date,
  ends_on       date,
  recurrence    jsonb,
  season        text,
  source        text not null default 'curated' check (source in ('curated','feed','provider')),
  priority      int  not null default 0,
  valid_from    timestamptz,
  valid_to      timestamptz,
  updated_at    timestamptz not null default now()
);

-- Drop the destination FK for DBs where an earlier 0007 created it (idempotent).
alter table public.local_signals drop constraint if exists local_signals_destination_id_fkey;

create index if not exists local_signals_dest_idx   on public.local_signals (destination_id);
create index if not exists local_signals_region_idx on public.local_signals (region_code);

alter table public.local_signals enable row level security;
do $$
begin
  create policy "read local_signals" on public.local_signals for select using (true);
exception when duplicate_object then null;
end $$;

insert into public.local_signals
  (id, destination_id, region_code, si, wells, kind, horizon, title, blurb, href, starts_on, ends_on, recurrence, season, source, priority, valid_from, valid_to) values
  ('mara-migration', 'masai-mara', '05A', '{"safari"}', '{"activities","stay"}', 'lookahead', 'soon', 'Great Migration river crossings', 'The herds reach the Mara and the famous crossings happen — roughly July to October. If that''s your window, it''s worth planning around.', '/guide/migration-timing', null, null, '{"months":[7,8,9,10]}'::jsonb, 'Jul–Oct', 'curated', 90, null, null),
  ('kyoto-sakura', 'kyoto', '08A', '{"culture"}', '{"activities","stay"}', 'lookahead', 'lookahead', 'Cherry blossom season', 'Sakura in Kyoto peaks late March into early April — brief, crowded, and unforgettable. Plan early if you''re chasing it.', '/guide/japan-cherry', null, null, '{"months":[3,4]}'::jsonb, 'late Mar–early Apr', 'curated', 80, null, null),
  ('patagonia-trekking', 'patagonia', '10S', '{"hiking"}', '{"activities","gear"}', 'schedule', 'lookahead', 'Patagonia trekking season', 'The W and the O trek best in the austral summer — roughly November to March, when the passes are open and the days are long.', '/guide/patagonia-trek', null, null, '{"months":[11,12,1,2,3]}'::jsonb, 'Nov–Mar', 'curated', 70, null, null),
  ('iceland-aurora', 'reykjavik', '03F', '{"globaladv"}', '{"activities","move"}', 'schedule', 'lookahead', 'Northern Lights season', 'Iceland''s aurora window runs roughly September to March, on clear dark nights away from town lights.', '/region/03F', null, null, '{"months":[9,10,11,12,1,2,3]}'::jsonb, 'Sep–Mar', 'curated', 65, null, null),
  ('med-sailing-season', null, '02F', '{"sailing","yacht"}', '{"activities","move"}', 'schedule', 'soon', 'Mediterranean sailing season', 'The Med sails best May through October — settled weather, warm water, and the islands at their easiest to hop.', '/guide/med-sailing', null, null, '{"months":[5,6,7,8,9,10]}'::jsonb, 'May–Oct', 'curated', 60, null, null),
  ('galapagos-hammerhead-season', 'galapagos', '10S', '{"liveaboard","ocean"}', '{"activities"}', 'lookahead', 'lookahead', 'Galápagos — schooling hammerheads at their peak', 'The cooler, plankton-rich months bring the big schools of hammerheads to Wolf and Darwin. Seas can be livelier then and the water cooler — a wetsuit and some dive experience help; liveaboards plan around the conditions.', null, null, null, '{"months":[6,7,8,9,10,11]}'::jsonb, 'Jun–Nov (cooler, plankton-rich, big schools)', 'curated', 90, null, null),
  ('raja-ampat-best-season', 'raja-ampat', '07A', '{"liveaboard","ocean"}', '{"activities"}', 'lookahead', 'lookahead', 'Raja Ampat — calmest seas, richest reefs', 'In the dry months the seas settle and the water turns clear and calm — easy, comfortable diving over the richest reefs on earth. Gentle enough that newer divers do well here.', null, null, null, '{"months":[10,11,12,1,2,3,4]}'::jsonb, 'Oct–Apr (dry season, best conditions)', 'curated', 90, null, null),
  ('maldives-manta-whaleshark', 'maldives', '07A', '{"liveaboard","ocean"}', '{"activities","stay"}', 'lookahead', 'lookahead', 'Maldives — mantas & whale sharks gather', 'As the seasonal currents shift, mantas and whale sharks gather to feed. The water is warm and generally easy year-round; a liveaboard follows the calm, clear conditions to where the giants are.', null, null, null, null, 'year-round; peak aggregations vary by atoll/monsoon', 'curated', 70, null, null),
  ('cocos-island-season', 'cocos-island', '10S', '{"liveaboard","ocean"}', '{"activities"}', 'lookahead', 'lookahead', 'Cocos Island (Costa Rica) — pelagic season', 'A legendary big-animal site reached by an open-ocean crossing (~30+ hours) — the passage can be rough and the dives have current, so it suits experienced divers. The reward: schooling hammerheads and big pelagics.', null, null, null, '{"months":[6,7,8,9,10,11]}'::jsonb, 'Jun–Nov (rainier topside, best big-animal action)', 'curated', 70, null, null),
  ('maldives-honeymoon-dry', 'maldives', '07A', '{"romance"}', '{"stay","activities"}', 'lookahead', 'lookahead', 'Maldives — the calm, clear honeymoon season', 'Dry skies and glassy, warm lagoon water — calm and clear for swimming straight off your overwater villa. The classic honeymoon for a reason.', null, null, null, '{"months":[11,12,1,2,3,4]}'::jsonb, 'Nov–Apr (dry season)', 'curated', 90, null, null),
  ('bora-bora-honeymoon-dry', 'bora-bora', '09P', '{"romance"}', '{"stay","activities"}', 'lookahead', 'lookahead', 'Bora Bora & French Polynesia — dry-season honeymoon', 'The lagoon everyone pictures — calm, warm, impossibly clear in the dry months. Gentle water you can wade and snorkel right from the shore.', null, null, null, '{"months":[5,6,7,8,9,10]}'::jsonb, 'May–Oct (dry season)', 'curated', 90, null, null),
  ('santorini-shoulder-romance', 'santorini', '02F', '{"romance"}', '{"stay"}', 'lookahead', 'lookahead', 'Santorini — golden shoulder-season romance', 'Late spring and early fall: warm light, fewer crowds, the caldera all to yourselves at sunset.', null, null, null, '{"months":[4,5,6,9,10]}'::jsonb, 'late Apr–Jun & Sep–Oct (shoulder)', 'curated', 80, null, null),
  ('caribbean-dry-season', 'caribbean', '11C', '{"tropical"}', '{"stay","activities"}', 'lookahead', 'lookahead', 'Caribbean — peak dry-season sunshine', 'The reliable warm-and-clear stretch — gentle trade winds, calm bays, easy swimming and snorkeling. When home is grey and cold, this is the dependable escape.', null, null, null, '{"months":[12,1,2,3,4]}'::jsonb, 'Dec–Apr (dry season; the escape-the-cold window)', 'curated', 90, null, null),
  ('turks-caicos-best', 'turks-caicos', '11C', '{"tropical","liveaboard"}', '{"stay","activities"}', 'lookahead', 'lookahead', 'Turks & Caicos — Grace Bay at its finest', 'Grace Bay at its finest — calm, clear, gentle water over white sand, easy for everyone from toddlers to snorkelers. Best in the dry months; see the honest note on hurricane season for timing. (Our backyard.)', null, null, null, '{"months":[12,1,2,3,4]}'::jsonb, 'Dec–Apr (dry, calm); Atlantic hurricane window Jun–Nov noted', 'curated', 90, null, null),
  ('bali-dry-season', 'bali', '07A', '{"tropical","culture"}', '{"stay","activities"}', 'lookahead', 'soon', 'Bali — the dry, golden season', 'The dry season brings clear days, calm coastal water, and soft evenings — the island at its most welcoming and easy.', '/destination/bali', null, null, '{"months":[4,5,6,7,8,9,10]}'::jsonb, 'Apr–Oct (dry season)', 'curated', 80, null, null),
  ('danube-classic-season', 'danube', '01F', '{"river","culture"}', '{"activities","stay"}', 'lookahead', 'lookahead', 'Danube — the classic cruising season', 'Vienna, Budapest, the Wachau in soft light — the heart of European river cruising.', null, null, null, '{"months":[4,5,6,7,8,9,10]}'::jsonb, 'Apr–Oct (cruising season)', 'curated', 80, null, null),
  ('danube-christmas-markets', 'danube', '01F', '{"river","culture"}', '{"activities","stay"}', 'lookahead', 'lookahead', 'Danube & Rhine — Christmas Markets cruises', 'Late November into December: the rivers glow with market lights. A magical, bookable window.', null, null, null, '{"months":[11,12]}'::jsonb, 'late Nov–Dec (Christmas markets)', 'curated', 80, null, null),
  ('rhine-classic-season', 'rhine', '01F', '{"river","culture","wine"}', '{"activities","stay"}', 'lookahead', 'lookahead', 'Rhine — castles, vineyards, the gorge', 'The storybook stretch — terraced vines and hilltop castles, best in the warm season.', null, null, null, '{"months":[4,5,6,7,8,9,10]}'::jsonb, 'Apr–Oct', 'curated', 70, null, null),
  ('douro-season', 'douro', '01F', '{"river","wine","culture"}', '{"activities","stay"}', 'lookahead', 'lookahead', 'Douro (Portugal) — wine country by water', 'Terraced port-wine valleys; the harvest months add a special glow.', null, null, null, '{"months":[4,5,6,7,8,9,10]}'::jsonb, 'Apr–Oct; harvest Sep–Oct', 'curated', 70, null, null),
  ('nile-best-season', 'nile', null, '{"river","culture"}', '{"activities","stay"}', 'lookahead', 'lookahead', 'Nile — the cooler cruising months', 'Temples and timeless river light, when the heat eases to comfortable.', null, null, null, '{"months":[10,11,12,1,2,3,4]}'::jsonb, 'Oct–Apr (cooler)', 'curated', 70, null, null),
  ('atlantic-hurricane-season-frame', 'caribbean', '11C', '{"tropical","liveaboard","romance"}', '{"stay","activities"}', 'lookahead', 'lookahead', 'Atlantic hurricane season — the honest, reassuring frame', 'Season runs Jun 1–Nov 30, but most major-hurricane activity is Aug–Oct (peak around mid-September). Most of the season, most places are doing exactly what you came for. And it''s never an ambush — systems are tracked days out, with warnings well ahead. Read the season, travel it wisely.', null, null, null, '{"months":[6,7,8,9,10,11]}'::jsonb, 'Jun 1–Nov 30; peak mid-Aug–mid-Oct', 'curated', 80, null, null),
  ('tci-hurricane-aware', 'turks-caicos', '11C', '{"tropical","liveaboard"}', '{"stay","activities"}', 'lookahead', 'lookahead', 'Turks & Caicos — hurricane-season straight talk', 'Our home waters, straight: T&C sits in the Atlantic corridor, so respect the Aug–Oct peak and plan a little. The flip side — the rest of the year is glorious, Grace Bay calm is the norm, and you''ll have days of warning if anything brews. Travel the shoulder months, protect your trip when you book, and you travel it like the locals: relaxed and ready.', null, null, null, '{"months":[8,9,10]}'::jsonb, 'respect Aug–Oct; relish the rest', 'curated', 80, null, null),
  ('southern-caribbean-below-belt', 'southern-caribbean', '11C', '{"tropical","liveaboard"}', '{"stay","activities"}', 'lookahead', 'lookahead', 'Southern Caribbean (Aruba/Bonaire/Curaçao) — below the hurricane belt', 'Happy geography: the ABC islands plus Trinidad & Tobago sit far enough south that most Atlantic storms pass to the north — widely known as below the hurricane belt, the lowest-risk corner of the Caribbean. Lower-risk isn''t no-risk, but for warm water with the calmest odds, the southern islands are a smart, sunny choice nearly year-round.', null, null, null, null, 'lowest-risk Caribbean zone, near year-round', 'curated', 70, null, null),
  ('honeymoon-hurricane-protect', 'caribbean', '11C', '{"romance","tropical"}', '{"stay","activities"}', 'lookahead', 'lookahead', 'Honeymoons — protect the once-in-a-lifetime trip', 'A honeymoon is worth protecting properly. The romance sweet spots (late fall through spring) sit largely outside the hurricane peak — calmest beaches, calmest skies. Book early, and add trip protection at the time you book (the detail couples most often miss): insurance covers storm disruption only if bought before a storm is named.', null, null, null, null, 'late fall–spring (outside peak)', 'curated', 80, null, null),
  ('dive-liveaboard-hurricane', 'caribbean', '11C', '{"liveaboard","ocean"}', '{"activities"}', 'lookahead', 'lookahead', 'Dive liveaboards — the pros watch the weather for you', 'Liveaboard trips are planned far ahead on tight weather windows — which works in your favor: operators watch the tropics professionally and reroute or reschedule around weather as routine. Book outside the Aug–Oct peak where you can, protect the trip when you reserve, and let the captain and the forecast do the worrying.', null, null, null, null, 'favor outside Aug–Oct peak', 'curated', 70, null, null)
on conflict (id) do update set
  destination_id = excluded.destination_id, region_code = excluded.region_code, si = excluded.si, wells = excluded.wells,
  kind = excluded.kind, horizon = excluded.horizon, title = excluded.title, blurb = excluded.blurb, href = excluded.href,
  starts_on = excluded.starts_on, ends_on = excluded.ends_on, recurrence = excluded.recurrence, season = excluded.season,
  source = excluded.source, priority = excluded.priority, valid_from = excluded.valid_from, valid_to = excluded.valid_to,
  updated_at = now();
