-- TravelWell.World — Local & temporal signals (Atlas's "knows what's happening").
--
-- GENERATED by scripts/gen-catalog-seed.ts from src/data/local-signals.ts.
-- Do not hand-edit — regenerate after authoring. Idempotent (ON CONFLICT).
-- World-readable: Atlas + Whispers read it; curated now, feeds/provider later.
--
-- Apply:  supabase db push   (or paste into the Supabase SQL editor)
-- Requires 0001 + 0002 (regions) and 0005 (destinations, for the FKs).

create table if not exists public.local_signals (
  id            text primary key,
  destination_id text references public.destinations(id) on delete cascade,
  region_code   text references public.regions(code),
  si            text[] not null default '{}',
  wells         text[] not null default '{}',
  kind          text not null check (kind in ('event','schedule','opening','lookahead')),
  horizon       text not null default 'now' check (horizon in ('now','soon','lookahead')),
  title         text not null,
  blurb         text,
  href          text,
  starts_on     date,
  ends_on       date,
  recurrence    jsonb,
  season        text,
  source        text not null default 'curated' check (source in ('curated','feed','provider')),
  priority      int  not null default 0,
  valid_from    timestamptz,
  valid_to      timestamptz,
  updated_at    timestamptz not null default now()
);

create index if not exists local_signals_dest_idx   on public.local_signals (destination_id);
create index if not exists local_signals_region_idx on public.local_signals (region_code);

alter table public.local_signals enable row level security;
do $$
begin
  create policy "read local_signals" on public.local_signals for select using (true);
exception when duplicate_object then null;
end $$;

insert into public.local_signals
  (id, destination_id, region_code, si, wells, kind, horizon, title, blurb, href, starts_on, ends_on, recurrence, season, source, priority, valid_from, valid_to) values
  ('mara-migration', 'masai-mara', '05A', '{"safari"}', '{"activities","stay"}', 'lookahead', 'soon', 'Great Migration river crossings', 'The herds reach the Mara and the famous crossings happen — roughly July to October. If that''s your window, it''s worth planning around.', '/guide/migration-timing', null, null, '{"months":[7,8,9,10]}'::jsonb, 'Jul–Oct', 'curated', 90, null, null),
  ('kyoto-sakura', 'kyoto', '08A', '{"culture"}', '{"activities","stay"}', 'lookahead', 'lookahead', 'Cherry blossom season', 'Sakura in Kyoto peaks late March into early April — brief, crowded, and unforgettable. Plan early if you''re chasing it.', '/guide/japan-cherry', null, null, '{"months":[3,4]}'::jsonb, 'late Mar–early Apr', 'curated', 80, null, null),
  ('patagonia-trekking', 'patagonia', '10S', '{"adventure"}', '{"activities","gear"}', 'schedule', 'lookahead', 'Patagonia trekking season', 'The W and the O trek best in the austral summer — roughly November to March, when the passes are open and the days are long.', '/guide/patagonia-trek', null, null, '{"months":[11,12,1,2,3]}'::jsonb, 'Nov–Mar', 'curated', 70, null, null),
  ('iceland-aurora', 'reykjavik', '03F', '{"photo"}', '{"activities","move"}', 'schedule', 'lookahead', 'Northern Lights season', 'Iceland''s aurora window runs roughly September to March, on clear dark nights away from town lights.', '/region/03F', null, null, '{"months":[9,10,11,12,1,2,3]}'::jsonb, 'Sep–Mar', 'curated', 65, null, null),
  ('med-sailing-season', null, '02F', '{"sailing","yacht"}', '{"activities","move"}', 'schedule', 'soon', 'Mediterranean sailing season', 'The Med sails best May through October — settled weather, warm water, and the islands at their easiest to hop.', '/guide/med-sailing', null, null, '{"months":[5,6,7,8,9,10]}'::jsonb, 'May–Oct', 'curated', 60, null, null),
  ('bali-dry-season', 'bali', '07A', '{"wellness","ocean"}', '{"activities","stay"}', 'schedule', 'soon', 'Bali''s dry season', 'April to October is Bali''s dry season — the easiest stretch for the rice terraces, the temples, and the surf.', '/destination/bali', null, null, '{"months":[4,5,6,7,8,9,10]}'::jsonb, 'Apr–Oct', 'curated', 50, null, null)
on conflict (id) do update set
  destination_id = excluded.destination_id, region_code = excluded.region_code, si = excluded.si, wells = excluded.wells,
  kind = excluded.kind, horizon = excluded.horizon, title = excluded.title, blurb = excluded.blurb, href = excluded.href,
  starts_on = excluded.starts_on, ends_on = excluded.ends_on, recurrence = excluded.recurrence, season = excluded.season,
  source = excluded.source, priority = excluded.priority, valid_from = excluded.valid_from, valid_to = excluded.valid_to,
  updated_at = now();
