/**
 * TravelWell.World — Local & temporal signals (the "knows what's happening"
 * layer behind Atlas + Well Whispers).
 *
 * Same authoring pattern as safety-data.ts: a typed, framework-free module you
 * (David) edit by hand. These curated "Tier A" entries are the offline-first
 * fallback and the seed for the public.local_signals table (migration 0007,
 * generated by scripts/gen-catalog-seed.ts) — so they're served from Postgres
 * and editable without a redeploy, while authored in the repo with review.
 *
 * Honesty contract (mirrors safety-data + Atlas's own rules): never fabricate a
 * dated "happening now." Curate things that are genuinely true and stable —
 * recurring seasons/schedules and well-known annual moments. Volatile "table
 * tonight" data is Tier C (provider-fed), not authored here. Every entry keeps
 * a `source`. `href` should be a real, working one-tap link.
 *
 * Keyed by destinations.id and/or regions.code, tagged by Special Interest and
 * Well so Atlas and the cross-link engine can find what's relevant.
 */

export type SignalKind = "event" | "schedule" | "opening" | "lookahead";
export type SignalHorizon = "now" | "soon" | "lookahead";

export interface LocalSignal {
  id: string;
  kind: SignalKind;
  horizon: SignalHorizon;
  title: string;
  blurb?: string;            // the gentle line, in Atlas's voice
  href?: string;             // real one-tap link (internal guide or external)
  destination?: string;      // destinations.id
  region?: string;           // regions.code
  si?: string[];             // relevant Special Interests
  wells?: string[];          // cross-link engine targets
  season?: string;           // human label, e.g. "Jul–Oct"
  recurrence?: { months?: number[]; days?: number[] }; // months 1-12, days 0-6 (Sun=0)
  startsOn?: string;         // ISO — for genuinely dated events
  endsOn?: string;           // ISO
  validFrom?: string;        // ISO — when to start surfacing
  validTo?: string;          // ISO
  priority?: number;
  source: "curated" | "feed" | "provider";
}

// Tier-A seed — a handful of real, stable seasonal signals tied to destinations
// and guides we already ship. Illustrative of the shape for David to expand;
// every one links to a real guide and states a genuinely recurring window.
export const LOCAL_SIGNALS: LocalSignal[] = [
  {
    id: "mara-migration",
    kind: "lookahead", horizon: "soon",
    title: "Great Migration river crossings",
    blurb: "The herds reach the Mara and the famous crossings happen — roughly July to October. If that's your window, it's worth planning around.",
    href: "/guide/migration-timing",
    destination: "masai-mara", region: "05A",
    si: ["safari"], wells: ["activities", "stay"],
    season: "Jul–Oct", recurrence: { months: [7, 8, 9, 10] },
    priority: 90, source: "curated",
  },
  {
    id: "kyoto-sakura",
    kind: "lookahead", horizon: "lookahead",
    title: "Cherry blossom season",
    blurb: "Sakura in Kyoto peaks late March into early April — brief, crowded, and unforgettable. Plan early if you're chasing it.",
    href: "/guide/japan-cherry",
    destination: "kyoto", region: "08A",
    si: ["culture"], wells: ["activities", "stay"],
    season: "late Mar–early Apr", recurrence: { months: [3, 4] },
    priority: 80, source: "curated",
  },
  {
    id: "patagonia-trekking",
    kind: "schedule", horizon: "lookahead",
    title: "Patagonia trekking season",
    blurb: "The W and the O trek best in the austral summer — roughly November to March, when the passes are open and the days are long.",
    href: "/guide/patagonia-trek",
    destination: "patagonia", region: "10S",
    si: ["adventure"], wells: ["activities", "gear"],
    season: "Nov–Mar", recurrence: { months: [11, 12, 1, 2, 3] },
    priority: 70, source: "curated",
  },
  {
    id: "iceland-aurora",
    kind: "schedule", horizon: "lookahead",
    title: "Northern Lights season",
    blurb: "Iceland's aurora window runs roughly September to March, on clear dark nights away from town lights.",
    href: "/region/03F",
    destination: "reykjavik", region: "03F",
    si: ["photo"], wells: ["activities", "move"],
    season: "Sep–Mar", recurrence: { months: [9, 10, 11, 12, 1, 2, 3] },
    priority: 65, source: "curated",
  },
  {
    id: "med-sailing-season",
    kind: "schedule", horizon: "soon",
    title: "Mediterranean sailing season",
    blurb: "The Med sails best May through October — settled weather, warm water, and the islands at their easiest to hop.",
    href: "/guide/med-sailing",
    region: "02F",
    si: ["sailing", "yacht"], wells: ["activities", "move"],
    season: "May–Oct", recurrence: { months: [5, 6, 7, 8, 9, 10] },
    priority: 60, source: "curated",
  },
  {
    id: "bali-dry-season",
    kind: "schedule", horizon: "soon",
    title: "Bali's dry season",
    blurb: "April to October is Bali's dry season — the easiest stretch for the rice terraces, the temples, and the surf.",
    href: "/destination/bali",
    destination: "bali", region: "07A",
    si: ["wellness", "ocean"], wells: ["activities", "stay"],
    season: "Apr–Oct", recurrence: { months: [4, 5, 6, 7, 8, 9, 10] },
    priority: 50, source: "curated",
  },
];

/** True when a signal's recurring window includes the given month (1-12). */
export function isActiveInMonth(s: LocalSignal, month: number): boolean {
  if (s.recurrence?.months?.length) return s.recurrence.months.includes(month);
  if (s.startsOn && s.endsOn) {
    const m = month;
    const a = new Date(s.startsOn).getMonth() + 1;
    const b = new Date(s.endsOn).getMonth() + 1;
    return a <= b ? m >= a && m <= b : m >= a || m <= b;
  }
  return true; // no temporal bound → always relevant
}

/**
 * Pure relevance filter usable on the bundle or DB rows: keep signals that match
 * the traveler's destination/region, overlap their Special Interests, and (when
 * `month` is given) sort the in-season ones first. Highest priority first.
 */
export function selectSignals(
  all: LocalSignal[],
  q: { destination?: string | null; region?: string | null; si?: string[]; month?: number }
): LocalSignal[] {
  const wantSi = q.si?.length ? new Set(q.si) : null;
  const matched = all.filter((s) => {
    const locOk =
      (!s.destination && !s.region) ||
      (q.destination && s.destination === q.destination) ||
      (q.region && s.region === q.region);
    if (!locOk) return false;
    if (wantSi && s.si?.length && !s.si.some((x) => wantSi.has(x))) return false;
    return true;
  });
  return matched.sort((a, b) => {
    if (q.month != null) {
      const ai = isActiveInMonth(a, q.month) ? 1 : 0;
      const bi = isActiveInMonth(b, q.month) ? 1 : 0;
      if (ai !== bi) return bi - ai;
    }
    return (b.priority ?? 0) - (a.priority ?? 0);
  });
}
