/**
 * TravelWell.World — Local & temporal signals (the "knows what's happening"
 * layer behind Atlas + Well Whispers).
 *
 * Authoring pattern mirrors safety-data.ts: a typed, framework-free module.
 * Curated "Tier A" entries are the offline-first fallback and the seed for the
 * public.local_signals table (migration 0007, generated by
 * scripts/gen-catalog-seed.ts) — served from Postgres, editable without a
 * redeploy, authored in the repo with review.
 *
 * Honesty contract (mirrors safety-data + Atlas's own rules): never fabricate a
 * dated "happening now." Curate things genuinely true and stable — recurring
 * seasons/schedules and well-known annual moments. Volatile "tonight" data is
 * Tier C (provider-fed), not authored here. Every entry keeps a `source`.
 *
 * CONTENT: David authors batches (in the LocalSignal shape) and Sana drops them
 * in here, normalizing SI tags to real keys + mapping regions. `destination` is
 * a free-text place key (NOT constrained to the destinations catalog), so
 * signals can name places we don't model yet.
 *
 * Keyed by destination and/or region, tagged by Special Interest and Well so
 * Atlas and the cross-link engine find what's relevant.
 */

export type SignalKind = "event" | "schedule" | "opening" | "lookahead";
export type SignalHorizon = "now" | "soon" | "lookahead";

export interface LocalSignal {
  id: string;
  kind: SignalKind;
  horizon: SignalHorizon;
  title: string;
  blurb?: string;            // the gentle line, in Atlas's voice
  href?: string;             // real one-tap link (internal guide or external)
  destination?: string;      // free-text place key (e.g. "raja-ampat")
  region?: string;           // regions.code
  si?: string[];             // relevant Special Interests (real taxonomy keys)
  wells?: string[];          // cross-link engine targets
  season?: string;           // human label, e.g. "Jul–Oct"
  recurrence?: { months?: number[]; days?: number[] }; // months 1-12, days 0-6 (Sun=0)
  startsOn?: string;         // ISO — for genuinely dated events
  endsOn?: string;           // ISO
  validFrom?: string;        // ISO — when to start surfacing
  validTo?: string;          // ISO
  priority?: number;
  source: "curated" | "feed" | "provider";
  // Structured extras for TLEU look-ahead events (ticket_drop / book_by /
  // sells_out / high_intent / upsell_ladder, …). Free-form so the event map
  // ingests without new columns per field.
  meta?: Record<string, unknown>;
}

export const LOCAL_SIGNALS: LocalSignal[] = [
  // ── Sana's originals (tied to destinations/guides we ship) ──────────────────
  {
    id: "mara-migration",
    kind: "lookahead", horizon: "soon",
    title: "Great Migration river crossings",
    blurb: "The herds reach the Mara and the famous crossings happen — roughly July to October. If that's your window, it's worth planning around.",
    href: "/guide/migration-timing",
    destination: "masai-mara", region: "05A",
    si: ["safari"], wells: ["activities", "stay"],
    season: "Jul–Oct", recurrence: { months: [7, 8, 9, 10] },
    priority: 90, source: "curated",
  },
  {
    id: "kyoto-sakura",
    kind: "lookahead", horizon: "lookahead",
    title: "Cherry blossom season",
    blurb: "Sakura in Kyoto peaks late March into early April — brief, crowded, and unforgettable. Plan early if you're chasing it.",
    href: "/guide/japan-cherry",
    destination: "kyoto", region: "08A",
    si: ["culture"], wells: ["activities", "stay"],
    season: "late Mar–early Apr", recurrence: { months: [3, 4] },
    priority: 80, source: "curated",
  },
  {
    id: "patagonia-trekking",
    kind: "schedule", horizon: "lookahead",
    title: "Patagonia trekking season",
    blurb: "The W and the O trek best in the austral summer — roughly November to March, when the passes are open and the days are long.",
    href: "/guide/patagonia-trek",
    destination: "patagonia", region: "10S",
    si: ["hiking"], wells: ["activities", "gear"],
    season: "Nov–Mar", recurrence: { months: [11, 12, 1, 2, 3] },
    priority: 70, source: "curated",
  },
  {
    id: "iceland-aurora",
    kind: "schedule", horizon: "lookahead",
    title: "Northern Lights season",
    blurb: "Iceland's aurora window runs roughly September to March, on clear dark nights away from town lights.",
    href: "/region/03F",
    destination: "reykjavik", region: "03F",
    si: ["adventure"], wells: ["activities", "move"],
    season: "Sep–Mar", recurrence: { months: [9, 10, 11, 12, 1, 2, 3] },
    priority: 65, source: "curated",
  },
  {
    id: "med-sailing-season",
    kind: "schedule", horizon: "soon",
    title: "Mediterranean sailing season",
    blurb: "The Med sails best May through October — settled weather, warm water, and the islands at their easiest to hop.",
    href: "/guide/med-sailing",
    region: "02F",
    si: ["sailing", "yacht"], wells: ["activities", "move"],
    season: "May–Oct", recurrence: { months: [5, 6, 7, 8, 9, 10] },
    priority: 60, source: "curated",
  },

  // ── David — Batch 1: Dive Liveaboards ───────────────────────────────────────
  {
    id: "galapagos-hammerhead-season",
    kind: "lookahead", horizon: "lookahead",
    title: "Galápagos — schooling hammerheads at their peak",
    blurb: "The cooler, plankton-rich months bring the big schools of hammerheads to Wolf and Darwin. Seas can be livelier then and the water cooler — a wetsuit and some dive experience help; liveaboards plan around the conditions.",
    destination: "galapagos", region: "10S",
    si: ["liveaboard", "ocean"], wells: ["activities"],
    season: "Jun–Nov (cooler, plankton-rich, big schools)", recurrence: { months: [6, 7, 8, 9, 10, 11] },
    priority: 90, source: "curated",
  },
  {
    id: "raja-ampat-best-season",
    kind: "lookahead", horizon: "lookahead",
    title: "Raja Ampat — calmest seas, richest reefs",
    blurb: "In the dry months the seas settle and the water turns clear and calm — easy, comfortable diving over the richest reefs on earth. Gentle enough that newer divers do well here.",
    destination: "raja-ampat", region: "07A",
    si: ["liveaboard", "ocean"], wells: ["activities"],
    season: "Oct–Apr (dry season, best conditions)", recurrence: { months: [10, 11, 12, 1, 2, 3, 4] },
    priority: 90, source: "curated",
  },
  {
    id: "maldives-manta-whaleshark",
    kind: "lookahead", horizon: "lookahead",
    title: "Maldives — mantas & whale sharks gather",
    blurb: "As the seasonal currents shift, mantas and whale sharks gather to feed. The water is warm and generally easy year-round; a liveaboard follows the calm, clear conditions to where the giants are.",
    destination: "maldives", region: "07A",
    si: ["liveaboard", "ocean"], wells: ["activities", "stay"],
    season: "year-round; peak aggregations vary by atoll/monsoon",
    priority: 70, source: "curated",
  },
  {
    id: "cocos-island-season",
    kind: "lookahead", horizon: "lookahead",
    title: "Cocos Island (Costa Rica) — pelagic season",
    blurb: "A legendary big-animal site reached by an open-ocean crossing (~30+ hours) — the passage can be rough and the dives have current, so it suits experienced divers. The reward: schooling hammerheads and big pelagics.",
    destination: "cocos-island", region: "10S",
    si: ["liveaboard", "ocean"], wells: ["activities"],
    season: "Jun–Nov (rainier topside, best big-animal action)", recurrence: { months: [6, 7, 8, 9, 10, 11] },
    priority: 70, source: "curated",
  },

  // ── David — Batch 1: Honeymoons ─────────────────────────────────────────────
  {
    id: "maldives-honeymoon-dry",
    kind: "lookahead", horizon: "lookahead",
    title: "Maldives — the calm, clear honeymoon season",
    blurb: "Dry skies and glassy, warm lagoon water — calm and clear for swimming straight off your overwater villa. The classic honeymoon for a reason.",
    destination: "maldives", region: "07A",
    si: ["romance"], wells: ["stay", "activities"],
    season: "Nov–Apr (dry season)", recurrence: { months: [11, 12, 1, 2, 3, 4] },
    priority: 90, source: "curated",
  },
  {
    id: "bora-bora-honeymoon-dry",
    kind: "lookahead", horizon: "lookahead",
    title: "Bora Bora & French Polynesia — dry-season honeymoon",
    blurb: "The lagoon everyone pictures — calm, warm, impossibly clear in the dry months. Gentle water you can wade and snorkel right from the shore.",
    destination: "bora-bora", region: "09P",
    si: ["romance"], wells: ["stay", "activities"],
    season: "May–Oct (dry season)", recurrence: { months: [5, 6, 7, 8, 9, 10] },
    priority: 90, source: "curated",
  },
  {
    id: "santorini-shoulder-romance",
    kind: "lookahead", horizon: "lookahead",
    title: "Santorini — golden shoulder-season romance",
    blurb: "Late spring and early fall: warm light, fewer crowds, the caldera all to yourselves at sunset.",
    destination: "santorini", region: "02F",
    si: ["romance"], wells: ["stay"],
    season: "late Apr–Jun & Sep–Oct (shoulder)", recurrence: { months: [4, 5, 6, 9, 10] },
    priority: 80, source: "curated",
  },

  // ── David — Batch 1: Tropical ───────────────────────────────────────────────
  {
    id: "caribbean-dry-season",
    kind: "lookahead", horizon: "lookahead",
    title: "Caribbean — peak dry-season sunshine",
    blurb: "The reliable warm-and-clear stretch — gentle trade winds, calm bays, easy swimming and snorkeling. When home is grey and cold, this is the dependable escape.",
    destination: "caribbean", region: "11C",
    si: ["tropical"], wells: ["stay", "activities"],
    season: "Dec–Apr (dry season; the escape-the-cold window)", recurrence: { months: [12, 1, 2, 3, 4] },
    priority: 90, source: "curated",
  },
  {
    id: "turks-caicos-best",
    kind: "lookahead", horizon: "lookahead",
    title: "Turks & Caicos — Grace Bay at its finest",
    blurb: "Grace Bay at its finest — calm, clear, gentle water over white sand, easy for everyone from toddlers to snorkelers. Best in the dry months; see the honest note on hurricane season for timing. (Our backyard.)",
    destination: "turks-caicos", region: "11C",
    si: ["tropical", "liveaboard"], wells: ["stay", "activities"],
    season: "Dec–Apr (dry, calm); Atlantic hurricane window Jun–Nov noted", recurrence: { months: [12, 1, 2, 3, 4] },
    priority: 90, source: "curated",
  },
  {
    id: "bali-dry-season",
    kind: "lookahead", horizon: "soon",
    title: "Bali — the dry, golden season",
    blurb: "The dry season brings clear days, calm coastal water, and soft evenings — the island at its most welcoming and easy.",
    href: "/destination/bali",
    destination: "bali", region: "07A",
    si: ["tropical", "culture"], wells: ["stay", "activities"],
    season: "Apr–Oct (dry season)", recurrence: { months: [4, 5, 6, 7, 8, 9, 10] },
    priority: 80, source: "curated",
  },

  // ── David — Batch 1: River Cruises ──────────────────────────────────────────
  {
    id: "danube-classic-season",
    kind: "lookahead", horizon: "lookahead",
    title: "Danube — the classic cruising season",
    blurb: "Vienna, Budapest, the Wachau in soft light — the heart of European river cruising.",
    destination: "danube", region: "01F",
    si: ["river", "culture"], wells: ["activities", "stay"],
    season: "Apr–Oct (cruising season)", recurrence: { months: [4, 5, 6, 7, 8, 9, 10] },
    priority: 80, source: "curated",
  },
  {
    id: "danube-christmas-markets",
    kind: "lookahead", horizon: "lookahead",
    title: "Danube & Rhine — Christmas Markets cruises",
    blurb: "Late November into December: the rivers glow with market lights. A magical, bookable window.",
    destination: "danube", region: "01F",
    si: ["river", "culture"], wells: ["activities", "stay"],
    season: "late Nov–Dec (Christmas markets)", recurrence: { months: [11, 12] },
    priority: 80, source: "curated",
  },
  {
    id: "rhine-classic-season",
    kind: "lookahead", horizon: "lookahead",
    title: "Rhine — castles, vineyards, the gorge",
    blurb: "The storybook stretch — terraced vines and hilltop castles, best in the warm season.",
    destination: "rhine", region: "01F",
    si: ["river", "culture", "wine"], wells: ["activities", "stay"],
    season: "Apr–Oct", recurrence: { months: [4, 5, 6, 7, 8, 9, 10] },
    priority: 70, source: "curated",
  },
  {
    id: "douro-season",
    kind: "lookahead", horizon: "lookahead",
    title: "Douro (Portugal) — wine country by water",
    blurb: "Terraced port-wine valleys; the harvest months add a special glow.",
    destination: "douro", region: "01F",
    si: ["river", "wine", "culture"], wells: ["activities", "stay"],
    season: "Apr–Oct; harvest Sep–Oct", recurrence: { months: [4, 5, 6, 7, 8, 9, 10] },
    priority: 70, source: "curated",
  },
  {
    id: "nile-best-season",
    kind: "lookahead", horizon: "lookahead",
    title: "Nile — the cooler cruising months",
    blurb: "Temples and timeless river light, when the heat eases to comfortable.",
    destination: "nile",
    si: ["river", "culture"], wells: ["activities", "stay"],
    season: "Oct–Apr (cooler)", recurrence: { months: [10, 11, 12, 1, 2, 3, 4] },
    priority: 70, source: "curated",
  },

  // ── David — Batch 1: Hurricane-awareness (Safer-Informed; pairs WITH the
  //    best-season signals, honest + reassuring, never fear-mongering) ──────────
  {
    id: "atlantic-hurricane-season-frame",
    kind: "lookahead", horizon: "lookahead",
    title: "Atlantic hurricane season — the honest, reassuring frame",
    blurb: "Season runs Jun 1–Nov 30, but most major-hurricane activity is Aug–Oct (peak around mid-September). Most of the season, most places are doing exactly what you came for. And it's never an ambush — systems are tracked days out, with warnings well ahead. Read the season, travel it wisely.",
    destination: "caribbean", region: "11C",
    si: ["tropical", "liveaboard", "romance"], wells: ["stay", "activities"],
    season: "Jun 1–Nov 30; peak mid-Aug–mid-Oct", recurrence: { months: [6, 7, 8, 9, 10, 11] },
    priority: 80, source: "curated",
  },
  {
    id: "tci-hurricane-aware",
    kind: "lookahead", horizon: "lookahead",
    title: "Turks & Caicos — hurricane-season straight talk",
    blurb: "Our home waters, straight: T&C sits in the Atlantic corridor, so respect the Aug–Oct peak and plan a little. The flip side — the rest of the year is glorious, Grace Bay calm is the norm, and you'll have days of warning if anything brews. Travel the shoulder months, protect your trip when you book, and you travel it like the locals: relaxed and ready.",
    destination: "turks-caicos", region: "11C",
    si: ["tropical", "liveaboard"], wells: ["stay", "activities"],
    season: "respect Aug–Oct; relish the rest", recurrence: { months: [8, 9, 10] },
    priority: 80, source: "curated",
  },
  {
    id: "southern-caribbean-below-belt",
    kind: "lookahead", horizon: "lookahead",
    title: "Southern Caribbean (Aruba/Bonaire/Curaçao) — below the hurricane belt",
    blurb: "Happy geography: the ABC islands plus Trinidad & Tobago sit far enough south that most Atlantic storms pass to the north — widely known as below the hurricane belt, the lowest-risk corner of the Caribbean. Lower-risk isn't no-risk, but for warm water with the calmest odds, the southern islands are a smart, sunny choice nearly year-round.",
    destination: "southern-caribbean", region: "11C",
    si: ["tropical", "liveaboard"], wells: ["stay", "activities"],
    season: "lowest-risk Caribbean zone, near year-round",
    priority: 70, source: "curated",
  },
  {
    id: "honeymoon-hurricane-protect",
    kind: "lookahead", horizon: "lookahead",
    title: "Honeymoons — protect the once-in-a-lifetime trip",
    blurb: "A honeymoon is worth protecting properly. The romance sweet spots (late fall through spring) sit largely outside the hurricane peak — calmest beaches, calmest skies. Book early, and add trip protection at the time you book (the detail couples most often miss): insurance covers storm disruption only if bought before a storm is named.",
    destination: "caribbean", region: "11C",
    si: ["romance", "tropical"], wells: ["stay", "activities"],
    season: "late fall–spring (outside peak)",
    priority: 80, source: "curated",
  },
  {
    id: "dive-liveaboard-hurricane",
    kind: "lookahead", horizon: "lookahead",
    title: "Dive liveaboards — the pros watch the weather for you",
    blurb: "Liveaboard trips are planned far ahead on tight weather windows — which works in your favor: operators watch the tropics professionally and reroute or reschedule around weather as routine. Book outside the Aug–Oct peak where you can, protect the trip when you reserve, and let the captain and the forecast do the worrying.",
    destination: "caribbean", region: "11C",
    si: ["liveaboard", "ocean"], wells: ["activities"],
    season: "favor outside Aug–Oct peak",
    priority: 70, source: "curated",
  },

  // ── David — Batch 2: Safari + Expedition (curated; variable windows framed soft) ──
  {
    id: "serengeti-calving",
    kind: "lookahead", horizon: "lookahead",
    title: "Serengeti calving — the great birth on the southern plains",
    blurb: "Late January into March, the southern Serengeti and Ndutu fill with newborn wildebeest — thousands a day — and the predators that follow. It's the most concentrated, most predictable stretch of the migration year; the exact start shifts a week or two with the short rains.",
    destination: "serengeti", region: "05A",
    si: ["safari"], wells: ["activities", "stay"],
    season: "late Jan–mid Mar (calving)", recurrence: { months: [1, 2, 3] },
    priority: 85, source: "curated",
  },
  {
    id: "okavango-flood-paradox",
    kind: "lookahead", horizon: "lookahead",
    title: "Okavango Delta — peak flood in the dry months",
    blurb: "The Delta's paradox: floodwaters from the Angolan highlands arrive in the dry season, peaking roughly June through August when local rain has stopped. That's mokoro and water-channel season — the iconic Okavango. Exact flood timing and reach vary year to year, so flexible dates and an operator's current read help.",
    destination: "okavango", region: "06A",
    si: ["safari"], wells: ["activities", "stay"],
    season: "peak flood ~Jun–Aug (varies yearly)", recurrence: { months: [6, 7, 8, 9] },
    priority: 80, source: "curated",
  },
  {
    id: "ngorongoro-crater-season",
    kind: "schedule", horizon: "lookahead",
    title: "Ngorongoro Crater — Big Five, any month",
    blurb: "The crater holds resident game year-round, so there's no bad month. June through October is driest, with the clearest views and the most predator action; the green months (Nov–May) bring lush scenery, fewer vehicles, and lower rates.",
    destination: "ngorongoro", region: "05A",
    si: ["safari"], wells: ["activities", "stay"],
    season: "year-round; Jun–Oct driest",
    priority: 70, source: "curated",
  },
  {
    id: "galapagos-whale-sharks",
    kind: "lookahead", horizon: "lookahead",
    title: "Galápagos — whale sharks at Darwin & Wolf",
    blurb: "From July into November the cool, plankton-rich upwelling draws giant — often pregnant — whale sharks to the far-northern islands of Darwin and Wolf. It's a liveaboard-dive window; the day boats don't reach that far.",
    destination: "galapagos", region: "10S",
    si: ["expedition", "ocean"], wells: ["activities"],
    season: "Jul–Nov (peak Jul–Oct)", recurrence: { months: [7, 8, 9, 10, 11] },
    priority: 80, source: "curated",
  },
  {
    id: "amazon-water-levels",
    kind: "schedule", horizon: "lookahead",
    title: "Amazon — high water vs low water changes the trip",
    blurb: "The Amazon has two faces. High water (roughly December–May) floods the forest, opening skiff routes into hidden creeks and lakes. Low water (roughly June–November) exposes riverbanks and sandbars for jungle walks. Neither is off-season — the water level just shifts what you do; the transition timing varies year to year.",
    destination: "amazon", region: "10S",
    si: ["expedition", "river"], wells: ["activities", "stay"],
    season: "high water ~Dec–May / low water ~Jun–Nov (varies yearly)",
    priority: 70, source: "curated",
  },

  // ── David — Batch 3 (verified 2026-06-25; variable natural events soft-framed; per-entry sources in David-Documentation/BATCH3-SIGNALS-VERIFIED.md) ──

  // Raja Ampat — liveaboard dry/calm season
  {
    id: "raja-ampat-dry-season",
    kind: "schedule", horizon: "lookahead",
    title: "Raja Ampat — calm seas, peak visibility",
    blurb: "The dry months bring calm seas and the clearest water over the richest reefs on earth — roughly October through April, with the glassiest conditions around January–February. Most liveaboards pause July–August in the windy season.",
    destination: "raja-ampat", region: "07A",
    si: ["liveaboard", "ocean"], wells: ["activities"],
    season: "Oct–Apr (calmest Jan–Feb; liveaboards pause Jul–Aug)", recurrence: { months: [10, 11, 12, 1, 2, 3, 4] },
    priority: 88, source: "curated",
  },
  // Galápagos — cool-season pelagics & whale sharks
  {
    id: "galapagos-cool-pelagic",
    kind: "lookahead", horizon: "lookahead",
    title: "Galápagos — the cool-season big animals",
    blurb: "The cool, plankton-rich Humboldt months — roughly June to November — bring the big pelagic action to Darwin and Wolf. Whale sharks are most reliable July through October; the seas run livelier and the water cooler, so it suits more experienced divers. Aggregations vary year to year.",
    destination: "galapagos", region: "10S",
    si: ["liveaboard", "ocean"], wells: ["activities"],
    season: "Jun–Nov cool season; whale sharks peak Jul–Oct (varies yearly)", recurrence: { months: [6, 7, 8, 9, 10, 11] },
    priority: 88, source: "curated",
  },
  // Red Sea (Egypt) — shoulder-season liveaboard window
  {
    id: "red-sea-best-season",
    kind: "schedule", horizon: "lookahead",
    title: "Red Sea — the calm shoulder-season window",
    blurb: "Calm seas and warm water make spring and autumn — roughly March–May and September–November — the sweet spot for Egyptian liveaboards. For sharks: scalloped hammerhead schools peak around May–July, and oceanic whitetips around October–December (varies yearly). Winter is divable but cooler.",
    destination: "red-sea", region: "04A",
    si: ["liveaboard", "ocean"], wells: ["activities"],
    season: "Mar–May & Sep–Nov (hammerheads ~May–Jul, oceanic whitetips ~Oct–Dec)", recurrence: { months: [3, 4, 5, 9, 10, 11] },
    priority: 78, source: "curated",
  },
  // Douro Valley — grape harvest (vindima)
  {
    id: "douro-harvest",
    kind: "lookahead", horizon: "lookahead",
    title: "Douro Valley — the grape harvest glow",
    blurb: "The vindima — harvest in the terraced port-wine valleys — runs roughly mid-September into mid-October, the most atmospheric stretch of the Douro cruising season. Exact picking dates shift year to year with the weather and the grapes.",
    destination: "douro", region: "01F",
    si: ["river", "wine", "culture"], wells: ["activities", "stay"],
    season: "harvest ~mid-Sep–mid-Oct (varies yearly); cruise season Apr–Oct", recurrence: { months: [9, 10] },
    priority: 76, source: "curated",
  },
  // Mekong — high-water season (Tonlé Sap access)
  {
    id: "mekong-high-water",
    kind: "lookahead", horizon: "lookahead",
    title: "Mekong — high water opens the great lake",
    blurb: "When the river runs high — roughly mid-August into November — ships can reach the Tonlé Sap and dock for the Siem Reap excursion. November is the rare sweet spot where high water and the cool, dry early-season weather overlap. Flood timing shifts year to year.",
    destination: "mekong", region: "07A",
    si: ["river", "culture"], wells: ["activities", "stay"],
    season: "high water ~mid-Aug–Nov (varies yearly); Nov = best weather + access", recurrence: { months: [8, 9, 10, 11] },
    priority: 76, source: "curated",
  },
  // Rhine — classic cruising season
  {
    id: "rhine-cruise-season",
    kind: "schedule", horizon: "lookahead",
    title: "Rhine — castles, vineyards, the gorge",
    blurb: "The Rhine cruises roughly April through October, with the warmest, busiest stretch June–August and the best-value light in the late-April–June and September shoulders. Late November into December brings the Christmas-market sailings.",
    destination: "rhine", region: "01F",
    si: ["river", "culture", "wine"], wells: ["activities", "stay"],
    season: "Apr–Oct (peak Jun–Aug); Christmas markets late Nov–Dec", recurrence: { months: [4, 5, 6, 7, 8, 9, 10] },
    priority: 74, source: "curated",
  },
  // Maldives — dry-season (NE monsoon)
  {
    id: "maldives-dry-season",
    kind: "schedule", horizon: "lookahead",
    title: "Maldives — the calm, clear dry season",
    blurb: "From November to April the northeast monsoon brings clear skies, gentle winds and glassy lagoon water — calm and warm for swimming straight off your villa. Peak conditions are December–March.",
    destination: "maldives", region: "07A",
    si: ["tropical"], wells: ["stay", "activities"],
    season: "Nov–Apr dry season (NE monsoon; peak Dec–Mar)", recurrence: { months: [11, 12, 1, 2, 3, 4] },
    priority: 86, source: "curated",
  },
  // Seychelles — calm trade-wind transitions
  {
    id: "seychelles-calm-transitions",
    kind: "lookahead", horizon: "lookahead",
    title: "Seychelles — the calm in between the trades",
    blurb: "Twice a year the trade winds change over and the sea goes glassy — roughly April–May and October–November. These transition months bring the calmest water and the best underwater visibility of the year.",
    destination: "seychelles", region: "07A",
    si: ["tropical"], wells: ["stay", "activities"],
    season: "Apr–May & Oct–Nov (trade-wind transitions, calmest seas)", recurrence: { months: [4, 5, 10, 11] },
    priority: 78, source: "curated",
  },
  // Fiji — dry season
  {
    id: "fiji-dry-season",
    kind: "schedule", horizon: "lookahead",
    title: "Fiji — the dry, golden season",
    blurb: "May through October is Fiji's dry season — cooler, less rain, steady trade winds and clear water for diving. The most settled months are June–August.",
    destination: "fiji", region: "09P",
    si: ["tropical"], wells: ["stay", "activities"],
    season: "May–Oct dry season (driest Jun–Aug)", recurrence: { months: [5, 6, 7, 8, 9, 10] },
    priority: 78, source: "curated",
  },
  // Santorini — golden shoulder-season romance
  {
    id: "santorini-shoulder",
    kind: "lookahead", horizon: "lookahead",
    title: "Santorini — warm light, fewer crowds",
    blurb: "Late spring and early autumn — roughly May–June and September into mid-October — bring warm seas, comfortable days and the caldera without the high-summer crush. Late September is many travelers' favorite.",
    destination: "santorini", region: "02F",
    si: ["romance"], wells: ["stay"],
    season: "May–Jun & Sep–mid-Oct (shoulder)", recurrence: { months: [5, 6, 9, 10] },
    priority: 80, source: "curated",
  },
  // Bali — dry season
  {
    id: "bali-dry-season-romance",
    kind: "schedule", horizon: "soon",
    title: "Bali — the dry, golden season",
    blurb: "Bali's dry season runs April through October — clear days, calm coastal water, soft evenings. May, June and September are the sweet spot, idyllic and quieter than the July–August peak.",
    destination: "bali", region: "07A",
    si: ["romance", "tropical"], wells: ["stay", "activities"],
    season: "Apr–Oct dry season (sweet spot May/Jun/Sep)", recurrence: { months: [4, 5, 6, 7, 8, 9, 10] },
    priority: 80, source: "curated",
  },
  // Amalfi Coast — shoulder-season romance
  {
    id: "amalfi-shoulder",
    kind: "lookahead", horizon: "lookahead",
    title: "Amalfi Coast — the warm, uncrowded edges",
    blurb: "May–June and September are the Amalfi sweet spot — warm, golden, and calmer than the August crush, with ferries and villages in full swing. The coast is open roughly April through October; in winter much of it closes down.",
    destination: "amalfi-coast", region: "02F",
    si: ["romance"], wells: ["stay", "activities"],
    season: "May–Jun & Sep shoulder (open ~Apr–Oct; winter largely closed)", recurrence: { months: [5, 6, 9] },
    priority: 78, source: "curated",
  },
  // South Luangwa — dry season & walking safaris
  {
    id: "south-luangwa-dry-walking",
    kind: "schedule", horizon: "lookahead",
    title: "South Luangwa — the walking-safari season",
    blurb: "As the dry season deepens — roughly June to October — game gathers along the Luangwa River and the thinned bush makes this the home of the walking safari, strongest from July on. Many camps close in the green months (~Nov–Apr).",
    destination: "south-luangwa", region: "06A",
    si: ["safari"], wells: ["activities", "stay"],
    season: "Jun–Oct dry (walking prime Jul–Oct; camps close ~Nov–Apr)", recurrence: { months: [6, 7, 8, 9, 10] },
    priority: 82, source: "curated",
  },
  // Etosha — dry-season waterholes
  {
    id: "etosha-dry-waterholes",
    kind: "schedule", horizon: "lookahead",
    title: "Etosha — the great waterhole gathering",
    blurb: "As the bush dries out — roughly May to October — animals are drawn to Etosha's waterholes, where you can watch many species drink in one spot. Concentrations build to a peak in September–October, just before the rains.",
    destination: "etosha", region: "06A",
    si: ["safari"], wells: ["activities", "stay"],
    season: "May–Oct dry (peak waterholes Sep–Oct)", recurrence: { months: [5, 6, 7, 8, 9, 10] },
    priority: 80, source: "curated",
  },
  // Svalbard — Arctic summer expedition season
  {
    id: "svalbard-arctic-summer",
    kind: "schedule", horizon: "lookahead",
    title: "Svalbard — the Arctic summer window",
    blurb: "The expedition-cruise season runs roughly late May through September, with the core June–August offering the warmest conditions and the best ice access to the remote north. Midnight sun lasts into late August; the season's edges shift year to year with the ice.",
    destination: "svalbard", region: "03F",
    si: ["expedition", "ocean"], wells: ["activities", "move"],
    season: "late May–Sep, core Jun–Aug (ice-dependent edges; midnight sun ~Apr 20–Aug 22)", recurrence: { months: [5, 6, 7, 8, 9] },
    priority: 80, source: "curated",
  },
  // Kimberley — dry-season expedition cruising
  {
    id: "kimberley-dry-expedition",
    kind: "schedule", horizon: "lookahead",
    title: "Kimberley — the dry-season expedition window",
    blurb: "The Kimberley coast cruises in the dry season — roughly April through September at the core, with March and October shoulders. Early in the window the waterfalls still run hard; by August–September humpbacks pass through.",
    destination: "kimberley", region: "09P",
    si: ["expedition", "ocean"], wells: ["activities", "move"],
    season: "Apr–Sep core (Mar/Oct shoulder); waterfalls early, whales Aug–Sep", recurrence: { months: [3, 4, 5, 6, 7, 8, 9, 10] },
    priority: 78, source: "curated",
  },
];

/** True when a signal's recurring window includes the given month (1-12). */
export function isActiveInMonth(s: LocalSignal, month: number): boolean {
  if (s.recurrence?.months?.length) return s.recurrence.months.includes(month);
  if (s.startsOn && s.endsOn) {
    const a = new Date(s.startsOn).getMonth() + 1;
    const b = new Date(s.endsOn).getMonth() + 1;
    return a <= b ? month >= a && month <= b : month >= a || month <= b;
  }
  return true; // no temporal bound → always relevant
}

/**
 * Pure relevance filter usable on the bundle or DB rows. A signal is relevant if
 * it matches the traveler's place (destination/region), OR overlaps their chosen
 * Special Interests (so dive-season signals surface for a diver even before they
 * land on a specific destination page), OR is global. Ranked: place-matches
 * first, then in-season, then priority.
 */
export function selectSignals(
  all: LocalSignal[],
  q: { destination?: string | null; region?: string | null; si?: string[]; month?: number }
): LocalSignal[] {
  const wantSi = q.si?.length ? new Set(q.si) : null;
  const scored = all
    .map((s) => {
      const placeMatch =
        (!!q.destination && s.destination === q.destination) || (!!q.region && s.region === q.region);
      const siMatch = !!wantSi && !!s.si?.some((x) => wantSi.has(x));
      const global = !s.destination && !s.region;
      return { s, placeMatch, keep: placeMatch || siMatch || global };
    })
    .filter((x) => x.keep);
  return scored
    .sort((a, b) => {
      if (a.placeMatch !== b.placeMatch) return a.placeMatch ? -1 : 1;
      if (q.month != null) {
        const ai = isActiveInMonth(a.s, q.month) ? 1 : 0;
        const bi = isActiveInMonth(b.s, q.month) ? 1 : 0;
        if (ai !== bi) return bi - ai;
      }
      return (b.s.priority ?? 0) - (a.s.priority ?? 0);
    })
    .map((x) => x.s);
}
